function a1=a1(s,xi)
global a alpha alphad betae cd eta G v h kpr kptr ktpr ktr kpz kptz ktpz ktz M md T0; 
a1=(xi.*(-2.*betae.^2.*cd.*eta.^2.*G.*M.*s.^2 + 2.*betae.*eta.^2.*G.*M.*(cd.*(kptr - kptz) + (ktpr - ktpz).*md).*s.*xi.^2 + alphad.^2.*cd.*s.*(1 + eta - v).*(s + (kpr - kpz).*M.*xi.^2) + ...
    alpha.*alphad.*M.*s.*(1 + eta - v).*(2.*betae.*cd.*s + (cd.*(-kptr + kptz) + (-ktpr + ktpz).*md).*xi.^2) + ...
    md.*(cd.*s.*(alpha.^2.*eta.*M.*s - alpha.^2.*M.*s.*(-1 + v) + 2.*eta.^2.*G.*(s + (kpr - kpz).*M.*xi.^2)) + xi.^2.*(alpha.^2.*eta.*(ktr - ktz).*M.*s - alpha.^2.*(ktr - ktz).*M.*s.*(-1 + v) + ...
        2.*eta.^2.*G.*((-(kptr - kptz)).*(ktpr - ktpz).*M.*xi.^2 + ktr.*(s + (kpr - kpz).*M.*xi.^2) - ktz.*(s + (kpr - kpz).*M.*xi.^2))))))./...
  (2.*eta.*G.*(-1 + v).*(2.*betae.^2.*cd.*eta.*G.*M.*s.^2 - 2.*betae.*eta.*G.*M.*(cd.*(kptr - kptz) + (ktpr - ktpz).*md).*s.*xi.^2 - alphad.^2.*cd.*s.*(s + (kpr - kpz).*M.*xi.^2) + ...
    alpha.*alphad.*M.*s.*(-2.*betae.*cd.*s + (cd.*(kptr - kptz) + (ktpr - ktpz).*md).*xi.^2) - ...
    md.*(cd.*s.*(alpha.^2.*M.*s + 2.*eta.*G.*(s + (kpr - kpz).*M.*xi.^2)) + xi.^2.*(alpha.^2.*(ktr - ktz).*M.*s + 2.*eta.*G.*((-(kptr - kptz)).*(ktpr - ktpz).*M.*xi.^2 + ...
          ktr.*(s + (kpr - kpz).*M.*xi.^2) - ktz.*(s + (kpr - kpz).*M.*xi.^2))))));
end