function a2=a2(s,xi)
global a alpha alphad betae cd eta G v h kpr kptr ktpr ktr kpz kptz ktpz ktz M md T0; 
a2=-((1./(2.*eta.*G)).*(xi.*(alpha + (alphad.*((-alpha).*alphad.*cd.*kptz.*M.*s + 2.*betae.*cd.*eta.*G.*kptz.*M.*s - alphad.^2.*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + ...
        alpha.*alphad.*ktpz.*M.*md.*s - 2.*betae.*eta.*G.*ktpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + ...
        2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2 + eta.*G.*kptz.*ktpz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*...
           (((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s + 2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + ...
              alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^...
             2 + 4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*...
             ((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s + md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + kpr.*ktpz.*M.*xi.^2))))) - ...
        eta.*G.*kpz.*ktz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s + ...
              2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - ...
              2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^2 + 4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + ...
                (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s + md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + ...
                  kpr.*ktpz.*M.*xi.^2)))))))./(2.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2))))));
end