function m4n=m4n(s,xi)
global a alpha alphad betae cd eta G v h kpr kptr ktpr ktr kpz kptz ktpz ktz M md T0; 
m4n=(a.*T0.*(-xi.^2 - (1./(4.*eta.*G.*(kptz.*ktpz - kpz.*ktz).*M.*md)).*((-alpha).*alphad.*cd.*kptz.*M.*s + 2.*betae.*cd.*eta.*G.*kptz.*M.*s + alphad.^2.*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s + ...
      2.*cd.*eta.*G.*kpz.*M.*md.*s - alpha.*alphad.*ktpz.*M.*md.*s + 2.*betae.*eta.*G.*ktpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 - 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 + ...
      2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2 + eta.*G.*kptz.*ktpz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*...
         (((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s + 2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + ...
            alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^2 + ...
          4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*...
           ((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s + md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + kpr.*ktpz.*M.*xi.^2))))) - ...
      eta.*G.*kpz.*ktz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s + ...
            2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - ...
            2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^2 + 4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + ...
            2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + ...
            2.*eta.*G.*(betae.*cd.*kpz.*M.*s + md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + kpr.*ktpz.*M.*xi.^2))))))).*besselj(1, a.*xi).*...
   ((h.*xi.^2.*(-2.*betae.^2.*cd.*eta.^2.*G.*M.*s.^2 + 2.*betae.*eta.^2.*G.*M.*(cd.*(kptr - kptz) + (ktpr - ktpz).*md).*s.*xi.^2 + alphad.^2.*cd.*s.*(1 + eta - v).*(s + (kpr - kpz).*M.*xi.^2) + ...
       alpha.*alphad.*M.*s.*(1 + eta - v).*(2.*betae.*cd.*s + (cd.*(-kptr + kptz) + (-ktpr + ktpz).*md).*xi.^2) + ...
       md.*(cd.*s.*(alpha.^2.*eta.*M.*s - alpha.^2.*M.*s.*(-1 + v) + 2.*eta.^2.*G.*(s + (kpr - kpz).*M.*xi.^2)) + xi.^2.*(alpha.^2.*eta.*(ktr - ktz).*M.*s - alpha.^2.*(ktr - ktz).*M.*s.*(-1 + v) + ...
           2.*eta.^2.*G.*((-(kptr - kptz)).*(ktpr - ktpz).*M.*xi.^2 + ktr.*(s + (kpr - kpz).*M.*xi.^2) - ktz.*(s + (kpr - kpz).*M.*xi.^2))))).*...
      (xi.^2 + (1./(4.*eta.*G.*(kptz.*ktpz - kpz.*ktz).*M.*md)).*((-alpha).*alphad.*cd.*kptz.*M.*s + 2.*betae.*cd.*eta.*G.*kptz.*M.*s + alphad.^2.*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s + ...
         2.*cd.*eta.*G.*kpz.*M.*md.*s - alpha.*alphad.*ktpz.*M.*md.*s + 2.*betae.*eta.*G.*ktpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 - 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 + ...
         2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2 - eta.*G.*kptz.*ktpz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*...
            (((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s + 2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + alpha.*alphad.*M.*...
                ((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^2 + ...
             4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*...
                M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s + md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + kpr.*ktpz.*M.*xi.^2))))) + ...
         eta.*G.*kpz.*ktz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*...
                s + 2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*...
                kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^2 + 4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + ...
                 (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s + md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + ...
                   kpr.*ktpz.*M.*xi.^2))))))).*sech(h.*xi).^2)./(2.*eta.*G.*(-1 + v).*(2.*betae.^2.*cd.*eta.*G.*M.*s.^2 - 2.*betae.*eta.*G.*M.*(cd.*(kptr - kptz) + (ktpr - ktpz).*md).*s.*xi.^2 - ...
       alphad.^2.*cd.*s.*(s + (kpr - kpz).*M.*xi.^2) + alpha.*alphad.*M.*s.*(-2.*betae.*cd.*s + (cd.*(kptr - kptz) + (ktpr - ktpz).*md).*xi.^2) - ...
       md.*(cd.*s.*(alpha.^2.*M.*s + 2.*eta.*G.*(s + (kpr - kpz).*M.*xi.^2)) + xi.^2.*(alpha.^2.*(ktr - ktz).*M.*s + 2.*eta.*G.*((-(kptr - kptz)).*(ktpr - ktpz).*M.*xi.^2 + ...
             ktr.*(s + (kpr - kpz).*M.*xi.^2) - ktz.*(s + (kpr - kpz).*M.*xi.^2)))))) + ...
    ((xi.^3.*(-2.*betae.^2.*cd.*eta.^2.*G.*M.*s.^2 + 2.*betae.*eta.^2.*G.*M.*(cd.*(kptr - kptz) + (ktpr - ktpz).*md).*s.*xi.^2 + alphad.^2.*cd.*s.*(1 + eta - v).*(s + (kpr - kpz).*M.*xi.^2) + ...
         alpha.*alphad.*M.*s.*(1 + eta - v).*(2.*betae.*cd.*s + (cd.*(-kptr + kptz) + (-ktpr + ktpz).*md).*xi.^2) + ...
         md.*(cd.*s.*(alpha.^2.*eta.*M.*s - alpha.^2.*M.*s.*(-1 + v) + 2.*eta.^2.*G.*(s + (kpr - kpz).*M.*xi.^2)) + xi.^2.*(alpha.^2.*eta.*(ktr - ktz).*M.*s - alpha.^2.*(ktr - ktz).*M.*s.*(-1 + v) + ...
             2.*eta.^2.*G.*((-(kptr - kptz)).*(ktpr - ktpz).*M.*xi.^2 + ktr.*(s + (kpr - kpz).*M.*xi.^2) - ktz.*(s + (kpr - kpz).*M.*xi.^2))))))./...
       (2.*eta.*G.*(-1 + v).*(2.*betae.^2.*cd.*eta.*G.*M.*s.^2 - 2.*betae.*eta.*G.*M.*(cd.*(kptr - kptz) + (ktpr - ktpz).*md).*s.*xi.^2 - alphad.^2.*cd.*s.*(s + (kpr - kpz).*M.*xi.^2) + ...
         alpha.*alphad.*M.*s.*(-2.*betae.*cd.*s + (cd.*(kptr - kptz) + (ktpr - ktpz).*md).*xi.^2) - md.*(cd.*s.*(alpha.^2.*M.*s + 2.*eta.*G.*(s + (kpr - kpz).*M.*xi.^2)) + ...
           xi.^2.*(alpha.^2.*(ktr - ktz).*M.*s + 2.*eta.*G.*((-(kptr - kptz)).*(ktpr - ktpz).*M.*xi.^2 + ktr.*(s + (kpr - kpz).*M.*xi.^2) - ktz.*(s + (kpr - kpz).*M.*xi.^2)))))) + ...
      (xi.*(-2.*betae.^2.*cd.*eta.^2.*G.*M.*s.^2 + 2.*betae.*eta.^2.*G.*M.*(cd.*(kptr - kptz) + (ktpr - ktpz).*md).*s.*xi.^2 + alphad.^2.*cd.*s.*(1 + eta - v).*(s + (kpr - kpz).*M.*xi.^2) + ...
         alpha.*alphad.*M.*s.*(1 + eta - v).*(2.*betae.*cd.*s + (cd.*(-kptr + kptz) + (-ktpr + ktpz).*md).*xi.^2) + ...
         md.*(cd.*s.*(alpha.^2.*eta.*M.*s - alpha.^2.*M.*s.*(-1 + v) + 2.*eta.^2.*G.*(s + (kpr - kpz).*M.*xi.^2)) + xi.^2.*(alpha.^2.*eta.*(ktr - ktz).*M.*s - alpha.^2.*(ktr - ktz).*M.*s.*(-1 + v) + ...
             2.*eta.^2.*G.*((-(kptr - kptz)).*(ktpr - ktpz).*M.*xi.^2 + ktr.*(s + (kpr - kpz).*M.*xi.^2) - ktz.*(s + (kpr - kpz).*M.*xi.^2))))).*...
        ((-alpha).*alphad.*cd.*kptz.*M.*s + 2.*betae.*cd.*eta.*G.*kptz.*M.*s + alphad.^2.*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s + 2.*cd.*eta.*G.*kpz.*M.*md.*s - alpha.*alphad.*ktpz.*M.*md.*s + ...
         2.*betae.*eta.*G.*ktpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 - 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 + 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + ...
         2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2 - eta.*G.*kptz.*ktpz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*...
            (((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s + 2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + alpha.*alphad.*M.*...
                ((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^2 + ...
             4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*...
                M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s + md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + kpr.*ktpz.*M.*xi.^2))))) + ...
         eta.*G.*kpz.*ktz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*...
                s + 2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*...
                kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^2 + 4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + ...
                 (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s + md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + ...
                   kpr.*ktpz.*M.*xi.^2)))))))./(8.*eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).*M.*md.*(-1 + v).*(2.*betae.^2.*cd.*eta.*G.*M.*s.^2 - 2.*betae.*eta.*G.*M.*(cd.*(kptr - kptz) + (ktpr - ktpz).*md).*...
          s.*xi.^2 - alphad.^2.*cd.*s.*(s + (kpr - kpz).*M.*xi.^2) + alpha.*alphad.*M.*s.*(-2.*betae.*cd.*s + (cd.*(kptr - kptz) + (ktpr - ktpz).*md).*xi.^2) - ...
         md.*(cd.*s.*(alpha.^2.*M.*s + 2.*eta.*G.*(s + (kpr - kpz).*M.*xi.^2)) + xi.^2.*(alpha.^2.*(ktr - ktz).*M.*s + 2.*eta.*G.*((-(kptr - kptz)).*(ktpr - ktpz).*M.*xi.^2 + ktr.*...
                (s + (kpr - kpz).*M.*xi.^2) - ktz.*(s + (kpr - kpz).*M.*xi.^2)))))) - (M.*s.*xi.^3.*(alphad.*cd.*(betae.*s + (-kptr + kptz).*xi.^2) + alpha.*md.*(cd.*s + (ktr - ktz).*xi.^2)).*...
        (alpha + (alphad.*((-alpha).*alphad.*cd.*kptz.*M.*s + 2.*betae.*cd.*eta.*G.*kptz.*M.*s - alphad.^2.*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + ...
            alpha.*alphad.*ktpz.*M.*md.*s - 2.*betae.*eta.*G.*ktpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - ...
            2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2 + eta.*G.*kptz.*ktpz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(...
                ((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s + 2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + ...
                  alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + ...
                  2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^2 + 4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*...
                 ((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s + md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + kpr.*ktpz.*M.*xi.^2))))) - ...
            eta.*G.*kpz.*ktz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + ...
                  alpha.^2.*ktz.*M.*md.*s + 2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + ...
                  2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^2 + 4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + ...
                  2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + ...
                  2.*eta.*G.*(betae.*cd.*kpz.*M.*s + md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + kpr.*ktpz.*M.*xi.^2)))))))./(2.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + ...
            2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)))))./(eta.*G.*(-2.*betae.^2.*cd.*eta.*G.*M.*s.^2 + 2.*betae.*eta.*G.*M.*(cd.*(kptr - kptz) + (ktpr - ktpz).*md).*...
          s.*xi.^2 + alphad.^2.*cd.*s.*(s + (kpr - kpz).*M.*xi.^2) + alpha.*alphad.*M.*s.*(2.*betae.*cd.*s + (cd.*(-kptr + kptz) + (-ktpr + ktpz).*md).*xi.^2) + ...
         md.*(cd.*s.*(alpha.^2.*M.*s + 2.*eta.*G.*(s + (kpr - kpz).*M.*xi.^2)) + xi.^2.*(alpha.^2.*(ktr - ktz).*M.*s + 2.*eta.*G.*((-(kptr - kptz)).*(ktpr - ktpz).*M.*xi.^2 + ktr.*...
                (s + (kpr - kpz).*M.*xi.^2) - ktz.*(s + (kpr - kpz).*M.*xi.^2))))))).*tanh(h.*xi) + ...
    (M.*s.*xi.^2.*(alphad.*cd.*(betae.*s + (-kptr + kptz).*xi.^2) + alpha.*md.*(cd.*s + (ktr - ktz).*xi.^2)).*...
      sqrt(-((1./(eta.*G.*(kptz.*ktpz - kpz.*ktz).*M.*md)).*((-alpha).*alphad.*cd.*kptz.*M.*s + 2.*betae.*cd.*eta.*G.*kptz.*M.*s + alphad.^2.*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s + ...
          2.*cd.*eta.*G.*kpz.*M.*md.*s - alpha.*alphad.*ktpz.*M.*md.*s + 2.*betae.*eta.*G.*ktpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 - 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 + ...
          2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2 - eta.*G.*kptz.*ktpz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*...
             (((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s + 2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + ...
                alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^...
               2 + 4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + ...
                alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s + md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + kpr.*ktpz.*M.*xi.^2))))) + ...
          eta.*G.*kpz.*ktz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + ...
                alpha.^2.*ktz.*M.*md.*s + 2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + ...
                2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^2 + 4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + ...
                2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + ...
                2.*eta.*G.*(betae.*cd.*kpz.*M.*s + md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + kpr.*ktpz.*M.*xi.^2)))))))).*...
      (alpha + (alphad.*((-alpha).*alphad.*cd.*kptz.*M.*s + 2.*betae.*cd.*eta.*G.*kptz.*M.*s - alphad.^2.*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + ...
          alpha.*alphad.*ktpz.*M.*md.*s - 2.*betae.*eta.*G.*ktpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - ...
          2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2 + eta.*G.*kptz.*ktpz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*...
             (((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s + 2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + ...
                alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^...
               2 + 4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + ...
                alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s + md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + kpr.*ktpz.*M.*xi.^2))))) - ...
          eta.*G.*kpz.*ktz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + ...
                alpha.^2.*ktz.*M.*md.*s + 2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + ...
                2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^2 + 4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + ...
                2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + ...
                2.*eta.*G.*(betae.*cd.*kpz.*M.*s + md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + kpr.*ktpz.*M.*xi.^2)))))))./(2.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + ...
          2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)))).*...
      tanh((1./2).*h.*sqrt(-((1./(eta.*G.*(kptz.*ktpz - kpz.*ktz).*M.*md)).*((-alpha).*alphad.*cd.*kptz.*M.*s + 2.*betae.*cd.*eta.*G.*kptz.*M.*s + alphad.^2.*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s + ...
            2.*cd.*eta.*G.*kpz.*M.*md.*s - alpha.*alphad.*ktpz.*M.*md.*s + 2.*betae.*eta.*G.*ktpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 - 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 + ...
            2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2 - eta.*G.*kptz.*ktpz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(...
                ((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s + 2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + ...
                  alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + ...
                  2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^2 + 4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*...
                 ((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s + md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + kpr.*ktpz.*M.*xi.^2))))) + ...
            eta.*G.*kpz.*ktz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + ...
                  alpha.^2.*ktz.*M.*md.*s + 2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + ...
                  2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^2 + 4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + ...
                  2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + ...
                  2.*eta.*G.*(betae.*cd.*kpz.*M.*s + md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + kpr.*ktpz.*M.*xi.^2))))))))))./...
     (2.*eta.*G.*(-2.*betae.^2.*cd.*eta.*G.*M.*s.^2 + 2.*betae.*eta.*G.*M.*(cd.*(kptr - kptz) + (ktpr - ktpz).*md).*s.*xi.^2 + alphad.^2.*cd.*s.*(s + (kpr - kpz).*M.*xi.^2) + ...
       alpha.*alphad.*M.*s.*(2.*betae.*cd.*s + (cd.*(-kptr + kptz) + (-ktpr + ktpz).*md).*xi.^2) + md.*(cd.*s.*(alpha.^2.*M.*s + 2.*eta.*G.*(s + (kpr - kpz).*M.*xi.^2)) + ...
         xi.^2.*(alpha.^2.*(ktr - ktz).*M.*s + 2.*eta.*G.*((-(kptr - kptz)).*(ktpr - ktpz).*M.*xi.^2 + ktr.*(s + (kpr - kpz).*M.*xi.^2) - ktz.*(s + (kpr - kpz).*M.*xi.^2))))))))./...
  (2.*s.*xi.*((h.*xi.^2.*(-2.*betae.^2.*cd.*eta.^2.*G.*M.*s.^2 + 2.*betae.*eta.^2.*G.*M.*(cd.*(kptr - kptz) + (ktpr - ktpz).*md).*s.*xi.^2 + alphad.^2.*cd.*s.*(1 + eta - v).*(s + (kpr - kpz).*M.*xi.^2) + ...
       alpha.*alphad.*M.*s.*(1 + eta - v).*(2.*betae.*cd.*s + (cd.*(-kptr + kptz) + (-ktpr + ktpz).*md).*xi.^2) + ...
       md.*(cd.*s.*(alpha.^2.*eta.*M.*s - alpha.^2.*M.*s.*(-1 + v) + 2.*eta.^2.*G.*(s + (kpr - kpz).*M.*xi.^2)) + xi.^2.*(alpha.^2.*eta.*(ktr - ktz).*M.*s - alpha.^2.*(ktr - ktz).*M.*s.*(-1 + v) + ...
           2.*eta.^2.*G.*((-(kptr - kptz)).*(ktpr - ktpz).*M.*xi.^2 + ktr.*(s + (kpr - kpz).*M.*xi.^2) - ktz.*(s + (kpr - kpz).*M.*xi.^2))))).*...
      (-xi.^2 - (1./(4.*eta.*G.*(kptz.*ktpz - kpz.*ktz).*M.*md)).*((-alpha).*alphad.*cd.*kptz.*M.*s + 2.*betae.*cd.*eta.*G.*kptz.*M.*s + alphad.^2.*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s + ...
         2.*cd.*eta.*G.*kpz.*M.*md.*s - alpha.*alphad.*ktpz.*M.*md.*s + 2.*betae.*eta.*G.*ktpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 - 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 + ...
         2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2 + eta.*G.*kptz.*ktpz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*...
            (((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s + 2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + alpha.*alphad.*M.*...
                ((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^2 + ...
             4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*...
                M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s + md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + kpr.*ktpz.*M.*xi.^2))))) - ...
         eta.*G.*kpz.*ktz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*...
                s + 2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*...
                kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^2 + 4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + ...
                 (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s + md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + ...
                   kpr.*ktpz.*M.*xi.^2))))))).*(((-alpha).*alphad.*cd.*kptz.*M.*s + 2.*betae.*cd.*eta.*G.*kptz.*M.*s - alphad.^2.*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + ...
         alpha.*alphad.*ktpz.*M.*md.*s - 2.*betae.*eta.*G.*ktpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + ...
         2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2 + eta.*G.*kptz.*ktpz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*...
            (((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s + 2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + alpha.*alphad.*M.*...
                ((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^2 + ...
             4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*...
                M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s + md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + kpr.*ktpz.*M.*xi.^2))))) - ...
         eta.*G.*kpz.*ktz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*...
                s + 2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*...
                kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^2 + 4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + ...
                 (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s + md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + ...
                   kpr.*ktpz.*M.*xi.^2))))))./(2.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2))) - ...
       ((-alpha).*alphad.*cd.*kptz.*M.*s + 2.*betae.*cd.*eta.*G.*kptz.*M.*s - alphad.^2.*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + alpha.*alphad.*ktpz.*M.*md.*s - ...
         2.*betae.*eta.*G.*ktpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + ...
         2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2 - eta.*G.*kptz.*ktpz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*...
            (((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s + 2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + alpha.*alphad.*M.*...
                ((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^2 + ...
             4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*...
                M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s + md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + kpr.*ktpz.*M.*xi.^2))))) + ...
         eta.*G.*kpz.*ktz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*...
                s + 2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*...
                kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^2 + 4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + ...
                 (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s + md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + ...
                   kpr.*ktpz.*M.*xi.^2))))))./(2.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)))).*...
      (-xi.^2 - (1./(4.*eta.*G.*(kptz.*ktpz - kpz.*ktz).*M.*md)).*((-alpha).*alphad.*cd.*kptz.*M.*s + 2.*betae.*cd.*eta.*G.*kptz.*M.*s + alphad.^2.*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s + ...
         2.*cd.*eta.*G.*kpz.*M.*md.*s - alpha.*alphad.*ktpz.*M.*md.*s + 2.*betae.*eta.*G.*ktpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 - 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 + ...
         2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2 - eta.*G.*kptz.*ktpz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*...
            (((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s + 2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + alpha.*alphad.*M.*...
                ((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^2 + ...
             4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*...
                M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s + md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + kpr.*ktpz.*M.*xi.^2))))) + ...
         eta.*G.*kpz.*ktz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*...
                s + 2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*...
                kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^2 + 4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + ...
                 (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s + md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + ...
                   kpr.*ktpz.*M.*xi.^2))))))).*sech(h.*xi).^2)./(2.*eta.*G.*(-1 + v).*(2.*betae.^2.*cd.*eta.*G.*M.*s.^2 - 2.*betae.*eta.*G.*M.*(cd.*(kptr - kptz) + (ktpr - ktpz).*md).*s.*xi.^2 - ...
       alphad.^2.*cd.*s.*(s + (kpr - kpz).*M.*xi.^2) + alpha.*alphad.*M.*s.*(-2.*betae.*cd.*s + (cd.*(kptr - kptz) + (ktpr - ktpz).*md).*xi.^2) - ...
       md.*(cd.*s.*(alpha.^2.*M.*s + 2.*eta.*G.*(s + (kpr - kpz).*M.*xi.^2)) + xi.^2.*(alpha.^2.*(ktr - ktz).*M.*s + 2.*eta.*G.*((-(kptr - kptz)).*(ktpr - ktpz).*M.*xi.^2 + ...
             ktr.*(s + (kpr - kpz).*M.*xi.^2) - ktz.*(s + (kpr - kpz).*M.*xi.^2)))))) + ...
    (-((1./(eta.*G)).*(xi.^3.*(alpha + (alphad.*((-alpha).*alphad.*cd.*kptz.*M.*s + 2.*betae.*cd.*eta.*G.*kptz.*M.*s - alphad.^2.*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + ...
             alpha.*alphad.*ktpz.*M.*md.*s - 2.*betae.*eta.*G.*ktpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - ...
             2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2 + eta.*G.*kptz.*ktpz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*...
                (((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s + 2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + ...
                   alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + ...
                   2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^2 + 4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*...
                  ((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s + md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + kpr.*ktpz.*M.*xi.^2))))) - ...
             eta.*G.*kpz.*ktz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + ...
                   alpha.^2.*ktz.*M.*md.*s + 2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + ...
                   2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^2 + 4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + ...
                   2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s + ...
                     md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + kpr.*ktpz.*M.*xi.^2)))))))./(2.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + ...
             2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)))).*(-xi.^2 - (1./(4.*eta.*G.*(kptz.*ktpz - kpz.*ktz).*M.*md)).*...
           ((-alpha).*alphad.*cd.*kptz.*M.*s + 2.*betae.*cd.*eta.*G.*kptz.*M.*s + alphad.^2.*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s + 2.*cd.*eta.*G.*kpz.*M.*md.*s - alpha.*alphad.*ktpz.*M.*md.*s + ...
            2.*betae.*eta.*G.*ktpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 - 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 + 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + ...
            2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2 + eta.*G.*kptz.*ktpz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - ...
                  2.*cd.*eta.*G.*kpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s + 2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*...
                   xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^2 + 4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + ...
                  2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + ...
                  2.*eta.*G.*(betae.*cd.*kpz.*M.*s + md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + kpr.*ktpz.*M.*xi.^2))))) - eta.*G.*kpz.*ktz.*M.*md.*...
             sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s + ...
                  2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - ...
                  2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^2 + 4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + ...
                    (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s + md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + ...
                      kpr.*ktpz.*M.*xi.^2))))))).*(-((s.*(alphad.*cd.*(s + (kpr - kpz).*M.*xi.^2) + alpha.*M.*(betae.*cd.*s + (-ktpr + ktpz).*md.*xi.^2)))./...
            (-2.*betae.^2.*cd.*eta.*G.*M.*s.^2 + 2.*betae.*eta.*G.*M.*(cd.*(kptr - kptz) + (ktpr - ktpz).*md).*s.*xi.^2 + alphad.^2.*cd.*s.*(s + (kpr - kpz).*M.*xi.^2) + ...
             alpha.*alphad.*M.*s.*(2.*betae.*cd.*s + (cd.*(-kptr + kptz) + (-ktpr + ktpz).*md).*xi.^2) + md.*(cd.*s.*(alpha.^2.*M.*s + 2.*eta.*G.*(s + (kpr - kpz).*M.*xi.^2)) + xi.^2.*...
                (alpha.^2.*(ktr - ktz).*M.*s + 2.*eta.*G.*((-(kptr - kptz)).*(ktpr - ktpz).*M.*xi.^2 + ktr.*(s + (kpr - kpz).*M.*xi.^2) - ktz.*(s + (kpr - kpz).*M.*xi.^2)))))) + ...
          (s.*(alphad.*cd.*(betae.*s + (-kptr + kptz).*xi.^2) + alpha.*md.*(cd.*s + (ktr - ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kptz.*M.*s + 2.*betae.*cd.*eta.*G.*kptz.*M.*s - ...
             alphad.^2.*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + alpha.*alphad.*ktpz.*M.*md.*s - 2.*betae.*eta.*G.*ktpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s - ...
             2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2 - ...
             eta.*G.*kptz.*ktpz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + ...
                   alpha.^2.*ktz.*M.*md.*s + 2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + ...
                   2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^2 + 4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + ...
                   2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s + ...
                     md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + kpr.*ktpz.*M.*xi.^2))))) + eta.*G.*kpz.*ktz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*...
                (((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s + 2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + ...
                   alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + ...
                   2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^2 + 4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*...
                  ((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s + md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + kpr.*ktpz.*M.*xi.^2)))))))./...
           (2.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*(-2.*betae.^2.*cd.*eta.*G.*M.*s.^2 + ...
             2.*betae.*eta.*G.*M.*(cd.*(kptr - kptz) + (ktpr - ktpz).*md).*s.*xi.^2 + alphad.^2.*cd.*s.*(s + (kpr - kpz).*M.*xi.^2) + alpha.*alphad.*M.*s.*...
              (2.*betae.*cd.*s + (cd.*(-kptr + kptz) + (-ktpr + ktpz).*md).*xi.^2) + md.*(cd.*s.*(alpha.^2.*M.*s + 2.*eta.*G.*(s + (kpr - kpz).*M.*xi.^2)) + xi.^2.*(alpha.^2.*(ktr - ktz).*M.*s + ...
                 2.*eta.*G.*((-(kptr - kptz)).*(ktpr - ktpz).*M.*xi.^2 + ktr.*(s + (kpr - kpz).*M.*xi.^2) - ktz.*(s + (kpr - kpz).*M.*xi.^2))))))))) + ...
      (xi.*(-2.*betae.^2.*cd.*eta.^2.*G.*M.*s.^2 + 2.*betae.*eta.^2.*G.*M.*(cd.*(kptr - kptz) + (ktpr - ktpz).*md).*s.*xi.^2 + alphad.^2.*cd.*s.*(1 + eta - v).*(s + (kpr - kpz).*M.*xi.^2) + ...
         alpha.*alphad.*M.*s.*(1 + eta - v).*(2.*betae.*cd.*s + (cd.*(-kptr + kptz) + (-ktpr + ktpz).*md).*xi.^2) + ...
         md.*(cd.*s.*(alpha.^2.*eta.*M.*s - alpha.^2.*M.*s.*(-1 + v) + 2.*eta.^2.*G.*(s + (kpr - kpz).*M.*xi.^2)) + xi.^2.*(alpha.^2.*eta.*(ktr - ktz).*M.*s - alpha.^2.*(ktr - ktz).*M.*s.*(-1 + v) + ...
             2.*eta.^2.*G.*((-(kptr - kptz)).*(ktpr - ktpz).*M.*xi.^2 + ktr.*(s + (kpr - kpz).*M.*xi.^2) - ktz.*(s + (kpr - kpz).*M.*xi.^2))))).*...
        (-xi.^2 - (1./(4.*eta.*G.*(kptz.*ktpz - kpz.*ktz).*M.*md)).*((-alpha).*alphad.*cd.*kptz.*M.*s + 2.*betae.*cd.*eta.*G.*kptz.*M.*s + alphad.^2.*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s + ...
           2.*cd.*eta.*G.*kpz.*M.*md.*s - alpha.*alphad.*ktpz.*M.*md.*s + 2.*betae.*eta.*G.*ktpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 - 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 + ...
           2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2 + eta.*G.*kptz.*ktpz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*...
              (((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s + 2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + ...
                 alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + ...
                 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^2 + 4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*...
                ((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s + md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + kpr.*ktpz.*M.*xi.^2))))) - ...
           eta.*G.*kpz.*ktz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + ...
                 alpha.^2.*ktz.*M.*md.*s + 2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + ...
                 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^2 + 4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + ...
                 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + ...
                 2.*eta.*G.*(betae.*cd.*kpz.*M.*s + md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + kpr.*ktpz.*M.*xi.^2))))))).*...
        (((-alpha).*alphad.*cd.*kptz.*M.*s + 2.*betae.*cd.*eta.*G.*kptz.*M.*s - alphad.^2.*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + alpha.*alphad.*ktpz.*M.*md.*s - ...
           2.*betae.*eta.*G.*ktpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + ...
           2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2 + eta.*G.*kptz.*ktpz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - ...
                 2.*cd.*eta.*G.*kpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s + 2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*...
                  xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^2 + 4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + ...
                 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + ...
                 2.*eta.*G.*(betae.*cd.*kpz.*M.*s + md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + kpr.*ktpz.*M.*xi.^2))))) - eta.*G.*kpz.*ktz.*M.*md.*...
            sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s + ...
                 2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - ...
                 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^2 + 4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + ...
                   (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s + md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + ...
                     kpr.*ktpz.*M.*xi.^2))))))./(2.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2))) - ...
         ((-alpha).*alphad.*cd.*kptz.*M.*s + 2.*betae.*cd.*eta.*G.*kptz.*M.*s - alphad.^2.*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + alpha.*alphad.*ktpz.*M.*md.*s - ...
           2.*betae.*eta.*G.*ktpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + ...
           2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2 - eta.*G.*kptz.*ktpz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - ...
                 2.*cd.*eta.*G.*kpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s + 2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*...
                  xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^2 + 4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + ...
                 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + ...
                 2.*eta.*G.*(betae.*cd.*kpz.*M.*s + md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + kpr.*ktpz.*M.*xi.^2))))) + eta.*G.*kpz.*ktz.*M.*md.*...
            sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s + ...
                 2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - ...
                 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^2 + 4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + ...
                   (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s + md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + ...
                     kpr.*ktpz.*M.*xi.^2))))))./(2.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)))).*...
        (-xi.^2 - (1./(4.*eta.*G.*(kptz.*ktpz - kpz.*ktz).*M.*md)).*((-alpha).*alphad.*cd.*kptz.*M.*s + 2.*betae.*cd.*eta.*G.*kptz.*M.*s + alphad.^2.*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s + ...
           2.*cd.*eta.*G.*kpz.*M.*md.*s - alpha.*alphad.*ktpz.*M.*md.*s + 2.*betae.*eta.*G.*ktpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 - 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 + ...
           2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2 - eta.*G.*kptz.*ktpz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*...
              (((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s + 2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + ...
                 alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + ...
                 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^2 + 4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*...
                ((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s + md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + kpr.*ktpz.*M.*xi.^2))))) + ...
           eta.*G.*kpz.*ktz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + ...
                 alpha.^2.*ktz.*M.*md.*s + 2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + ...
                 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^2 + 4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + ...
                 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + ...
                 2.*eta.*G.*(betae.*cd.*kpz.*M.*s + md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + kpr.*ktpz.*M.*xi.^2))))))))./...
       (2.*eta.*G.*(-1 + v).*(2.*betae.^2.*cd.*eta.*G.*M.*s.^2 - 2.*betae.*eta.*G.*M.*(cd.*(kptr - kptz) + (ktpr - ktpz).*md).*s.*xi.^2 - alphad.^2.*cd.*s.*(s + (kpr - kpz).*M.*xi.^2) + ...
         alpha.*alphad.*M.*s.*(-2.*betae.*cd.*s + (cd.*(kptr - kptz) + (ktpr - ktpz).*md).*xi.^2) - md.*(cd.*s.*(alpha.^2.*M.*s + 2.*eta.*G.*(s + (kpr - kpz).*M.*xi.^2)) + ...
           xi.^2.*(alpha.^2.*(ktr - ktz).*M.*s + 2.*eta.*G.*((-(kptr - kptz)).*(ktpr - ktpz).*M.*xi.^2 + ktr.*(s + (kpr - kpz).*M.*xi.^2) - ktz.*(s + (kpr - kpz).*M.*xi.^2)))))) + ...
      (1./(eta.*G)).*(xi.^3.*(-((s.*(alphad.*cd.*(s + (kpr - kpz).*M.*xi.^2) + alpha.*M.*(betae.*cd.*s + (-ktpr + ktpz).*md.*xi.^2)))./(-2.*betae.^2.*cd.*eta.*G.*M.*s.^2 + ...
            2.*betae.*eta.*G.*M.*(cd.*(kptr - kptz) + (ktpr - ktpz).*md).*s.*xi.^2 + alphad.^2.*cd.*s.*(s + (kpr - kpz).*M.*xi.^2) + ...
            alpha.*alphad.*M.*s.*(2.*betae.*cd.*s + (cd.*(-kptr + kptz) + (-ktpr + ktpz).*md).*xi.^2) + md.*(cd.*s.*(alpha.^2.*M.*s + 2.*eta.*G.*(s + (kpr - kpz).*M.*xi.^2)) + ...
              xi.^2.*(alpha.^2.*(ktr - ktz).*M.*s + 2.*eta.*G.*((-(kptr - kptz)).*(ktpr - ktpz).*M.*xi.^2 + ktr.*(s + (kpr - kpz).*M.*xi.^2) - ktz.*(s + (kpr - kpz).*M.*xi.^2)))))) + ...
         (s.*(alphad.*cd.*(betae.*s + (-kptr + kptz).*xi.^2) + alpha.*md.*(cd.*s + (ktr - ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kptz.*M.*s + 2.*betae.*cd.*eta.*G.*kptz.*M.*s - ...
            alphad.^2.*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + alpha.*alphad.*ktpz.*M.*md.*s - 2.*betae.*eta.*G.*ktpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s - ...
            2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2 + ...
            eta.*G.*kptz.*ktpz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + ...
                  alpha.^2.*ktz.*M.*md.*s + 2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + ...
                  2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^2 + 4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + ...
                  2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + ...
                  2.*eta.*G.*(betae.*cd.*kpz.*M.*s + md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + kpr.*ktpz.*M.*xi.^2))))) - eta.*G.*kpz.*ktz.*M.*md.*...
             sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s + ...
                  2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - ...
                  2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^2 + 4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + ...
                    (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s + md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + ...
                      kpr.*ktpz.*M.*xi.^2)))))))./(2.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*...
           (-2.*betae.^2.*cd.*eta.*G.*M.*s.^2 + 2.*betae.*eta.*G.*M.*(cd.*(kptr - kptz) + (ktpr - ktpz).*md).*s.*xi.^2 + alphad.^2.*cd.*s.*(s + (kpr - kpz).*M.*xi.^2) + ...
            alpha.*alphad.*M.*s.*(2.*betae.*cd.*s + (cd.*(-kptr + kptz) + (-ktpr + ktpz).*md).*xi.^2) + md.*(cd.*s.*(alpha.^2.*M.*s + 2.*eta.*G.*(s + (kpr - kpz).*M.*xi.^2)) + ...
              xi.^2.*(alpha.^2.*(ktr - ktz).*M.*s + 2.*eta.*G.*((-(kptr - kptz)).*(ktpr - ktpz).*M.*xi.^2 + ktr.*(s + (kpr - kpz).*M.*xi.^2) - ktz.*(s + (kpr - kpz).*M.*xi.^2))))))).*...
        (alpha + (alphad.*((-alpha).*alphad.*cd.*kptz.*M.*s + 2.*betae.*cd.*eta.*G.*kptz.*M.*s - alphad.^2.*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + ...
            alpha.*alphad.*ktpz.*M.*md.*s - 2.*betae.*eta.*G.*ktpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - ...
            2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2 - eta.*G.*kptz.*ktpz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(...
                ((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s + 2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + ...
                  alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + ...
                  2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^2 + 4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*...
                 ((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s + md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + kpr.*ktpz.*M.*xi.^2))))) + ...
            eta.*G.*kpz.*ktz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + ...
                  alpha.^2.*ktz.*M.*md.*s + 2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + ...
                  2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^2 + 4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + ...
                  2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + ...
                  2.*eta.*G.*(betae.*cd.*kpz.*M.*s + md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + kpr.*ktpz.*M.*xi.^2)))))))./(2.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + ...
            2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)))).*(-xi.^2 - (1./(4.*eta.*G.*(kptz.*ktpz - kpz.*ktz).*M.*md)).*...
          ((-alpha).*alphad.*cd.*kptz.*M.*s + 2.*betae.*cd.*eta.*G.*kptz.*M.*s + alphad.^2.*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s + 2.*cd.*eta.*G.*kpz.*M.*md.*s - alpha.*alphad.*ktpz.*M.*md.*s + ...
           2.*betae.*eta.*G.*ktpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 - 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 + 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + ...
           2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2 - eta.*G.*kptz.*ktpz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - ...
                 2.*cd.*eta.*G.*kpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s + 2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*...
                  xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^2 + 4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + ...
                 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + ...
                 2.*eta.*G.*(betae.*cd.*kpz.*M.*s + md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + kpr.*ktpz.*M.*xi.^2))))) + eta.*G.*kpz.*ktz.*M.*md.*...
            sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s + ...
                 2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - ...
                 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^2 + 4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + ...
                   (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s + md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + ...
                     kpr.*ktpz.*M.*xi.^2))))))))).*tanh(h.*xi) - ...
    (1./(2.*eta.*G)).*(xi.^2.*sqrt(-((1./(eta.*G.*(kptz.*ktpz - kpz.*ktz).*M.*md)).*((-alpha).*alphad.*cd.*kptz.*M.*s + 2.*betae.*cd.*eta.*G.*kptz.*M.*s + alphad.^2.*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s + ...
          2.*cd.*eta.*G.*kpz.*M.*md.*s - alpha.*alphad.*ktpz.*M.*md.*s + 2.*betae.*eta.*G.*ktpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 - 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 + ...
          2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2 + eta.*G.*kptz.*ktpz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*...
             (((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s + 2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + ...
                alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^...
               2 + 4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + ...
                alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s + md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + kpr.*ktpz.*M.*xi.^2))))) - ...
          eta.*G.*kpz.*ktz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + ...
                alpha.^2.*ktz.*M.*md.*s + 2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + ...
                2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^2 + 4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + ...
                2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + ...
                2.*eta.*G.*(betae.*cd.*kpz.*M.*s + md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + kpr.*ktpz.*M.*xi.^2)))))))).*...
      (-((s.*(alphad.*cd.*(s + (kpr - kpz).*M.*xi.^2) + alpha.*M.*(betae.*cd.*s + (-ktpr + ktpz).*md.*xi.^2)))./(-2.*betae.^2.*cd.*eta.*G.*M.*s.^2 + ...
          2.*betae.*eta.*G.*M.*(cd.*(kptr - kptz) + (ktpr - ktpz).*md).*s.*xi.^2 + alphad.^2.*cd.*s.*(s + (kpr - kpz).*M.*xi.^2) + ...
          alpha.*alphad.*M.*s.*(2.*betae.*cd.*s + (cd.*(-kptr + kptz) + (-ktpr + ktpz).*md).*xi.^2) + md.*(cd.*s.*(alpha.^2.*M.*s + 2.*eta.*G.*(s + (kpr - kpz).*M.*xi.^2)) + ...
            xi.^2.*(alpha.^2.*(ktr - ktz).*M.*s + 2.*eta.*G.*((-(kptr - kptz)).*(ktpr - ktpz).*M.*xi.^2 + ktr.*(s + (kpr - kpz).*M.*xi.^2) - ktz.*(s + (kpr - kpz).*M.*xi.^2)))))) + ...
       (s.*(alphad.*cd.*(betae.*s + (-kptr + kptz).*xi.^2) + alpha.*md.*(cd.*s + (ktr - ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kptz.*M.*s + 2.*betae.*cd.*eta.*G.*kptz.*M.*s - alphad.^2.*cd.*kpz.*M.*s + ...
          2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + alpha.*alphad.*ktpz.*M.*md.*s - 2.*betae.*eta.*G.*ktpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + ...
          2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2 + eta.*G.*kptz.*ktpz.*M.*md.*...
           sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s + ...
                2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - ...
                2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^2 + 4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + ...
                  (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s + md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + ...
                    kpr.*ktpz.*M.*xi.^2))))) - eta.*G.*kpz.*ktz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - ...
                2.*cd.*eta.*G.*kpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s + 2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + ...
                2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^2 + 4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + ...
                2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + ...
                2.*eta.*G.*(betae.*cd.*kpz.*M.*s + md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + kpr.*ktpz.*M.*xi.^2)))))))./(2.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + ...
          2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*(-2.*betae.^2.*cd.*eta.*G.*M.*s.^2 + 2.*betae.*eta.*G.*M.*(cd.*(kptr - kptz) + (ktpr - ktpz).*md).*s.*xi.^2 + ...
          alphad.^2.*cd.*s.*(s + (kpr - kpz).*M.*xi.^2) + alpha.*alphad.*M.*s.*(2.*betae.*cd.*s + (cd.*(-kptr + kptz) + (-ktpr + ktpz).*md).*xi.^2) + ...
          md.*(cd.*s.*(alpha.^2.*M.*s + 2.*eta.*G.*(s + (kpr - kpz).*M.*xi.^2)) + xi.^2.*(alpha.^2.*(ktr - ktz).*M.*s + 2.*eta.*G.*((-(kptr - kptz)).*(ktpr - ktpz).*M.*xi.^2 + ...
                ktr.*(s + (kpr - kpz).*M.*xi.^2) - ktz.*(s + (kpr - kpz).*M.*xi.^2))))))).*...
      (alpha + (alphad.*((-alpha).*alphad.*cd.*kptz.*M.*s + 2.*betae.*cd.*eta.*G.*kptz.*M.*s - alphad.^2.*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + ...
          alpha.*alphad.*ktpz.*M.*md.*s - 2.*betae.*eta.*G.*ktpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - ...
          2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2 - eta.*G.*kptz.*ktpz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*...
             (((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s + 2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + ...
                alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^...
               2 + 4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + ...
                alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s + md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + kpr.*ktpz.*M.*xi.^2))))) + ...
          eta.*G.*kpz.*ktz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + ...
                alpha.^2.*ktz.*M.*md.*s + 2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + ...
                2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^2 + 4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + ...
                2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + ...
                2.*eta.*G.*(betae.*cd.*kpz.*M.*s + md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + kpr.*ktpz.*M.*xi.^2)))))))./(2.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + ...
          2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)))).*(-xi.^2 - (1./(4.*eta.*G.*(kptz.*ktpz - kpz.*ktz).*M.*md)).*...
        ((-alpha).*alphad.*cd.*kptz.*M.*s + 2.*betae.*cd.*eta.*G.*kptz.*M.*s + alphad.^2.*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s + 2.*cd.*eta.*G.*kpz.*M.*md.*s - alpha.*alphad.*ktpz.*M.*md.*s + ...
         2.*betae.*eta.*G.*ktpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 - 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 + 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + ...
         2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2 - eta.*G.*kptz.*ktpz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*...
            (((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s + 2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + alpha.*alphad.*M.*...
                ((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^2 + ...
             4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*...
                M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s + md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + kpr.*ktpz.*M.*xi.^2))))) + ...
         eta.*G.*kpz.*ktz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*...
                s + 2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*...
                kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^2 + 4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + ...
                 (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s + md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + ...
                   kpr.*ktpz.*M.*xi.^2))))))).*tanh((1./2).*h.*sqrt(-((1./(eta.*G.*(kptz.*ktpz - kpz.*ktz).*M.*md)).*((-alpha).*alphad.*cd.*kptz.*M.*s + 2.*betae.*cd.*eta.*G.*kptz.*M.*s + ...
            alphad.^2.*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s + 2.*cd.*eta.*G.*kpz.*M.*md.*s - alpha.*alphad.*ktpz.*M.*md.*s + 2.*betae.*eta.*G.*ktpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s - ...
            2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 - 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 + 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2 + ...
            eta.*G.*kptz.*ktpz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + ...
                  alpha.^2.*ktz.*M.*md.*s + 2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + ...
                  2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^2 + 4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + ...
                  2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + ...
                  2.*eta.*G.*(betae.*cd.*kpz.*M.*s + md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + kpr.*ktpz.*M.*xi.^2))))) - eta.*G.*kpz.*ktz.*M.*md.*...
             sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s + ...
                  2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - ...
                  2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^2 + 4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + ...
                    (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s + md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + ...
                      kpr.*ktpz.*M.*xi.^2)))))))))) - ...
    (1./(2.*eta.*G)).*(xi.^2.*sqrt(-((1./(eta.*G.*(kptz.*ktpz - kpz.*ktz).*M.*md)).*((-alpha).*alphad.*cd.*kptz.*M.*s + 2.*betae.*cd.*eta.*G.*kptz.*M.*s + alphad.^2.*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s + ...
          2.*cd.*eta.*G.*kpz.*M.*md.*s - alpha.*alphad.*ktpz.*M.*md.*s + 2.*betae.*eta.*G.*ktpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 - 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 + ...
          2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2 - eta.*G.*kptz.*ktpz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*...
             (((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s + 2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + ...
                alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^...
               2 + 4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + ...
                alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s + md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + kpr.*ktpz.*M.*xi.^2))))) + ...
          eta.*G.*kpz.*ktz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + ...
                alpha.^2.*ktz.*M.*md.*s + 2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + ...
                2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^2 + 4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + ...
                2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + ...
                2.*eta.*G.*(betae.*cd.*kpz.*M.*s + md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + kpr.*ktpz.*M.*xi.^2)))))))).*...
      (alpha + (alphad.*((-alpha).*alphad.*cd.*kptz.*M.*s + 2.*betae.*cd.*eta.*G.*kptz.*M.*s - alphad.^2.*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + ...
          alpha.*alphad.*ktpz.*M.*md.*s - 2.*betae.*eta.*G.*ktpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - ...
          2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2 + eta.*G.*kptz.*ktpz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*...
             (((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s + 2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + ...
                alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^...
               2 + 4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + ...
                alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s + md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + kpr.*ktpz.*M.*xi.^2))))) - ...
          eta.*G.*kpz.*ktz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + ...
                alpha.^2.*ktz.*M.*md.*s + 2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + ...
                2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^2 + 4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + ...
                2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + ...
                2.*eta.*G.*(betae.*cd.*kpz.*M.*s + md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + kpr.*ktpz.*M.*xi.^2)))))))./(2.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + ...
          2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)))).*(xi.^2 + (1./(4.*eta.*G.*(kptz.*ktpz - kpz.*ktz).*M.*md)).*...
        ((-alpha).*alphad.*cd.*kptz.*M.*s + 2.*betae.*cd.*eta.*G.*kptz.*M.*s + alphad.^2.*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s + 2.*cd.*eta.*G.*kpz.*M.*md.*s - alpha.*alphad.*ktpz.*M.*md.*s + ...
         2.*betae.*eta.*G.*ktpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 - 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 + 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + ...
         2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2 + eta.*G.*kptz.*ktpz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*...
            (((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s + 2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + alpha.*alphad.*M.*...
                ((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^2 + ...
             4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*...
                M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s + md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + kpr.*ktpz.*M.*xi.^2))))) - ...
         eta.*G.*kpz.*ktz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*...
                s + 2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*...
                kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^2 + 4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + ...
                 (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s + md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + ...
                   kpr.*ktpz.*M.*xi.^2))))))).*(-((s.*(alphad.*cd.*(s + (kpr - kpz).*M.*xi.^2) + alpha.*M.*(betae.*cd.*s + (-ktpr + ktpz).*md.*xi.^2)))./...
         (-2.*betae.^2.*cd.*eta.*G.*M.*s.^2 + 2.*betae.*eta.*G.*M.*(cd.*(kptr - kptz) + (ktpr - ktpz).*md).*s.*xi.^2 + alphad.^2.*cd.*s.*(s + (kpr - kpz).*M.*xi.^2) + ...
          alpha.*alphad.*M.*s.*(2.*betae.*cd.*s + (cd.*(-kptr + kptz) + (-ktpr + ktpz).*md).*xi.^2) + md.*(cd.*s.*(alpha.^2.*M.*s + 2.*eta.*G.*(s + (kpr - kpz).*M.*xi.^2)) + ...
            xi.^2.*(alpha.^2.*(ktr - ktz).*M.*s + 2.*eta.*G.*((-(kptr - kptz)).*(ktpr - ktpz).*M.*xi.^2 + ktr.*(s + (kpr - kpz).*M.*xi.^2) - ktz.*(s + (kpr - kpz).*M.*xi.^2)))))) + ...
       (s.*(alphad.*cd.*(betae.*s + (-kptr + kptz).*xi.^2) + alpha.*md.*(cd.*s + (ktr - ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kptz.*M.*s + 2.*betae.*cd.*eta.*G.*kptz.*M.*s - alphad.^2.*cd.*kpz.*M.*s + ...
          2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + alpha.*alphad.*ktpz.*M.*md.*s - 2.*betae.*eta.*G.*ktpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + ...
          2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2 - eta.*G.*kptz.*ktpz.*M.*md.*...
           sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s + ...
                2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - ...
                2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^2 + 4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + ...
                  (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s + md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + ...
                    kpr.*ktpz.*M.*xi.^2))))) + eta.*G.*kpz.*ktz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - ...
                2.*cd.*eta.*G.*kpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s + 2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + ...
                2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^2 + 4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + ...
                2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + ...
                2.*eta.*G.*(betae.*cd.*kpz.*M.*s + md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + kpr.*ktpz.*M.*xi.^2)))))))./(2.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + ...
          2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*(-2.*betae.^2.*cd.*eta.*G.*M.*s.^2 + 2.*betae.*eta.*G.*M.*(cd.*(kptr - kptz) + (ktpr - ktpz).*md).*s.*xi.^2 + ...
          alphad.^2.*cd.*s.*(s + (kpr - kpz).*M.*xi.^2) + alpha.*alphad.*M.*s.*(2.*betae.*cd.*s + (cd.*(-kptr + kptz) + (-ktpr + ktpz).*md).*xi.^2) + ...
          md.*(cd.*s.*(alpha.^2.*M.*s + 2.*eta.*G.*(s + (kpr - kpz).*M.*xi.^2)) + xi.^2.*(alpha.^2.*(ktr - ktz).*M.*s + 2.*eta.*G.*((-(kptr - kptz)).*(ktpr - ktpz).*M.*xi.^2 + ...
                ktr.*(s + (kpr - kpz).*M.*xi.^2) - ktz.*(s + (kpr - kpz).*M.*xi.^2))))))).*...
      tanh((1./2).*h.*sqrt(-((1./(eta.*G.*(kptz.*ktpz - kpz.*ktz).*M.*md)).*((-alpha).*alphad.*cd.*kptz.*M.*s + 2.*betae.*cd.*eta.*G.*kptz.*M.*s + alphad.^2.*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s + ...
            2.*cd.*eta.*G.*kpz.*M.*md.*s - alpha.*alphad.*ktpz.*M.*md.*s + 2.*betae.*eta.*G.*ktpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 - 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 + ...
            2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2 - eta.*G.*kptz.*ktpz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(...
                ((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s + 2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + ...
                  alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + ...
                  2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^2 + 4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*...
                 ((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s + md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + kpr.*ktpz.*M.*xi.^2))))) + ...
            eta.*G.*kpz.*ktz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((-alphad.^2).*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + ...
                  alpha.^2.*ktz.*M.*md.*s + 2.*betae.*eta.*G.*M.*(cd.*kptz - ktpz.*md).*s + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md).*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + ...
                  2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2).^2 + 4.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + ...
                  2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + ...
                  2.*eta.*G.*(betae.*cd.*kpz.*M.*s + md.*(ktpz.*s - kpz.*ktpr.*M.*xi.^2 + kpr.*ktpz.*M.*xi.^2))))))))))));
end