function m7n=m7n(s,xi)
global a alpha alphad betae cd eta G v h kpr kptr ktpr ktr kpz kptz ktpz ktz M md T0; 
m7n=-((a.*T0.*besselj(1, a.*xi).*...
    ((-((xi.*((alpha.*alphad.*s - 2.*betae.*eta.*G.*s + 2.*eta.*G.*kptr.*xi.^2)./(eta.*G.*kptz) + (1./(eta.*G.*kptz.*(kptz.*ktpz - kpz.*ktz).*M.*md)).*...
            ((-(cd.*kptz.*((-alpha).*alphad.*kptz + 2.*betae.*eta.*G.*kptz + alphad.^2.*kpz).*M + alpha.*(alpha.*kptz - alphad.*kpz).*ktz.*M.*md + 2.*eta.*G.*(betae.*kpz.*ktz.*M + kptz.*(ktz + cd.*kpz.*M)).*md)).*s + ...
             2.*eta.*G.*(kptz.^2.*ktpr + kptr.*kpz.*ktz - kptz.*(kpz.*ktr + kpr.*ktz)).*M.*md.*xi.^2) + sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*...
             (((cd.*(2.*betae.*eta.*G.*kptz - alphad.^2.*kpz).*M + alpha.^2.*ktz.*M.*md + 2.*eta.*G.*(ktz - (cd.*kpz + betae.*ktpz).*M).*md + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md)).*s + ...
                2.*eta.*G.*((-kptz).*ktpr + kptr.*ktpz - kpz.*ktr + kpr.*ktz).*M.*md.*xi.^2).^2 - 4.*M.*((-alphad.^2).*cd.*kptz.*s + alpha.*alphad.*ktz.*md.*s - 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + ...
                  (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s - kpz.*ktpr.*M.*md.*xi.^2 + ktpz.*md.*(s + kpr.*M.*xi.^2)))))).*...
          ((alphad.^3.*cd.*kpz.*M + alpha.^2.*alphad.*ktz.*M.*md + 2.*alphad.*eta.*G.*((-betae).*cd.*kptz.*M - ktz.*md + cd.*kpz.*M.*md + betae.*ktpz.*M.*md) - ...
             alpha.*M.*(4.*eta.*G.*(cd.*kptz + betae.*ktz).*md + alphad.^2.*(cd.*kptz + ktpz.*md))).*s + 2.*eta.*G.*(alphad.*(kptz.*ktpr - kptr.*ktpz + kpz.*ktr - kpr.*ktz) + alpha.*(-2.*kptz.*ktr + 2.*kptr.*ktz)).*M.*md.*...
            xi.^2 + alphad.*eta.*G.*kptz.*ktpz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((cd.*(2.*betae.*eta.*G.*kptz - alphad.^2.*kpz).*M + alpha.^2.*ktz.*M.*md + ...
                   2.*eta.*G.*(ktz - (cd.*kpz + betae.*ktpz).*M).*md + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md)).*s + 2.*eta.*G.*((-kptz).*ktpr + kptr.*ktpz - kpz.*ktr + kpr.*ktz).*M.*md.*xi.^2).^2 - 4.*M.*...
                ((-alphad.^2).*cd.*kptz.*s + alpha.*alphad.*ktz.*md.*s - 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + ...
                 2.*eta.*G.*(betae.*cd.*kpz.*M.*s - kpz.*ktpr.*M.*md.*xi.^2 + ktpz.*md.*(s + kpr.*M.*xi.^2))))) - alphad.*eta.*G.*kpz.*ktz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*...
              (((cd.*(2.*betae.*eta.*G.*kptz - alphad.^2.*kpz).*M + alpha.^2.*ktz.*M.*md + 2.*eta.*G.*(ktz - (cd.*kpz + betae.*ktpz).*M).*md + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md)).*s + ...
                 2.*eta.*G.*((-kptz).*ktpr + kptr.*ktpz - kpz.*ktr + kpr.*ktz).*M.*md.*xi.^2).^2 - 4.*M.*((-alphad.^2).*cd.*kptz.*s + alpha.*alphad.*ktz.*md.*s - 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + ...
                   (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s - kpz.*ktpr.*M.*md.*xi.^2 + ktpz.*md.*(s + kpr.*M.*xi.^2)))))))./...
         (16.*eta.*G.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)))) + ...
       (xi.*((alpha.*alphad.*s - 2.*betae.*eta.*G.*s + 2.*eta.*G.*kptr.*xi.^2)./(eta.*G.*kptz) + (1./(eta.*G.*kptz.*(kptz.*ktpz - kpz.*ktz).*M.*md)).*...
           ((-(cd.*kptz.*((-alpha).*alphad.*kptz + 2.*betae.*eta.*G.*kptz + alphad.^2.*kpz).*M + alpha.*(alpha.*kptz - alphad.*kpz).*ktz.*M.*md + 2.*eta.*G.*(betae.*kpz.*ktz.*M + kptz.*(ktz + cd.*kpz.*M)).*md)).*s + ...
            2.*eta.*G.*(kptz.^2.*ktpr + kptr.*kpz.*ktz - kptz.*(kpz.*ktr + kpr.*ktz)).*M.*md.*xi.^2) - sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*...
            (((cd.*(2.*betae.*eta.*G.*kptz - alphad.^2.*kpz).*M + alpha.^2.*ktz.*M.*md + 2.*eta.*G.*(ktz - (cd.*kpz + betae.*ktpz).*M).*md + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md)).*s + 2.*eta.*G.*...
                ((-kptz).*ktpr + kptr.*ktpz - kpz.*ktr + kpr.*ktz).*M.*md.*xi.^2).^2 - 4.*M.*((-alphad.^2).*cd.*kptz.*s + alpha.*alphad.*ktz.*md.*s - 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + ...
                 (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s - kpz.*ktpr.*M.*md.*xi.^2 + ktpz.*md.*(s + kpr.*M.*xi.^2)))))).*...
         ((alphad.^3.*cd.*kpz.*M + alpha.^2.*alphad.*ktz.*M.*md + 2.*alphad.*eta.*G.*((-betae).*cd.*kptz.*M - ktz.*md + cd.*kpz.*M.*md + betae.*ktpz.*M.*md) - ...
            alpha.*M.*(4.*eta.*G.*(cd.*kptz + betae.*ktz).*md + alphad.^2.*(cd.*kptz + ktpz.*md))).*s + 2.*eta.*G.*(alphad.*(kptz.*ktpr - kptr.*ktpz + kpz.*ktr - kpr.*ktz) + alpha.*(-2.*kptz.*ktr + 2.*kptr.*ktz)).*M.*md.*...
           xi.^2 - alphad.*eta.*G.*kptz.*ktpz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((cd.*(2.*betae.*eta.*G.*kptz - alphad.^2.*kpz).*M + alpha.^2.*ktz.*M.*md + ...
                  2.*eta.*G.*(ktz - (cd.*kpz + betae.*ktpz).*M).*md + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md)).*s + 2.*eta.*G.*((-kptz).*ktpr + kptr.*ktpz - kpz.*ktr + kpr.*ktz).*M.*md.*xi.^2).^2 - ...
              4.*M.*((-alphad.^2).*cd.*kptz.*s + alpha.*alphad.*ktz.*md.*s - 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + ...
                2.*eta.*G.*(betae.*cd.*kpz.*M.*s - kpz.*ktpr.*M.*md.*xi.^2 + ktpz.*md.*(s + kpr.*M.*xi.^2))))) + alphad.*eta.*G.*kpz.*ktz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*...
             (((cd.*(2.*betae.*eta.*G.*kptz - alphad.^2.*kpz).*M + alpha.^2.*ktz.*M.*md + 2.*eta.*G.*(ktz - (cd.*kpz + betae.*ktpz).*M).*md + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md)).*s + ...
                2.*eta.*G.*((-kptz).*ktpr + kptr.*ktpz - kpz.*ktr + kpr.*ktz).*M.*md.*xi.^2).^2 - 4.*M.*((-alphad.^2).*cd.*kptz.*s + alpha.*alphad.*ktz.*md.*s - 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + ...
                  (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s - kpz.*ktpr.*M.*md.*xi.^2 + ktpz.*md.*(s + kpr.*M.*xi.^2)))))))./...
        (16.*eta.*G.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2))) + ...
       xi.^2.*((xi.*((alphad.^3.*cd.*kpz.*M + alpha.^2.*alphad.*ktz.*M.*md + 2.*alphad.*eta.*G.*((-betae).*cd.*kptz.*M - ktz.*md + cd.*kpz.*M.*md + betae.*ktpz.*M.*md) - alpha.*M.*(4.*eta.*G.*(cd.*kptz + betae.*ktz).*md + ...
                alphad.^2.*(cd.*kptz + ktpz.*md))).*s + 2.*eta.*G.*(alphad.*(kptz.*ktpr - kptr.*ktpz + kpz.*ktr - kpr.*ktz) + alpha.*(-2.*kptz.*ktr + 2.*kptr.*ktz)).*M.*md.*xi.^2 + ...
            alphad.*eta.*G.*kptz.*ktpz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((cd.*(2.*betae.*eta.*G.*kptz - alphad.^2.*kpz).*M + alpha.^2.*ktz.*M.*md + ...
                    2.*eta.*G.*(ktz - (cd.*kpz + betae.*ktpz).*M).*md + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md)).*s + 2.*eta.*G.*((-kptz).*ktpr + kptr.*ktpz - kpz.*ktr + kpr.*ktz).*M.*md.*xi.^2).^2 - ...
                4.*M.*((-alphad.^2).*cd.*kptz.*s + alpha.*alphad.*ktz.*md.*s - 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + ...
                  2.*eta.*G.*(betae.*cd.*kpz.*M.*s - kpz.*ktpr.*M.*md.*xi.^2 + ktpz.*md.*(s + kpr.*M.*xi.^2))))) - alphad.*eta.*G.*kpz.*ktz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(...
                ((cd.*(2.*betae.*eta.*G.*kptz - alphad.^2.*kpz).*M + alpha.^2.*ktz.*M.*md + 2.*eta.*G.*(ktz - (cd.*kpz + betae.*ktpz).*M).*md + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md)).*s + ...
                  2.*eta.*G.*((-kptz).*ktpr + kptr.*ktpz - kpz.*ktr + kpr.*ktz).*M.*md.*xi.^2).^2 - 4.*M.*((-alphad.^2).*cd.*kptz.*s + alpha.*alphad.*ktz.*md.*s - 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + ...
                    (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s - kpz.*ktpr.*M.*md.*xi.^2 + ktpz.*md.*(s + kpr.*M.*xi.^2)))))))./...
          (4.*eta.*G.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2))) - ...
         (xi.*((alphad.^3.*cd.*kpz.*M + alpha.^2.*alphad.*ktz.*M.*md + 2.*alphad.*eta.*G.*((-betae).*cd.*kptz.*M - ktz.*md + cd.*kpz.*M.*md + betae.*ktpz.*M.*md) - alpha.*M.*(4.*eta.*G.*(cd.*kptz + betae.*ktz).*md + ...
                alphad.^2.*(cd.*kptz + ktpz.*md))).*s + 2.*eta.*G.*(alphad.*(kptz.*ktpr - kptr.*ktpz + kpz.*ktr - kpr.*ktz) + alpha.*(-2.*kptz.*ktr + 2.*kptr.*ktz)).*M.*md.*xi.^2 - ...
            alphad.*eta.*G.*kptz.*ktpz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((cd.*(2.*betae.*eta.*G.*kptz - alphad.^2.*kpz).*M + alpha.^2.*ktz.*M.*md + ...
                    2.*eta.*G.*(ktz - (cd.*kpz + betae.*ktpz).*M).*md + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md)).*s + 2.*eta.*G.*((-kptz).*ktpr + kptr.*ktpz - kpz.*ktr + kpr.*ktz).*M.*md.*xi.^2).^2 - ...
                4.*M.*((-alphad.^2).*cd.*kptz.*s + alpha.*alphad.*ktz.*md.*s - 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + ...
                  2.*eta.*G.*(betae.*cd.*kpz.*M.*s - kpz.*ktpr.*M.*md.*xi.^2 + ktpz.*md.*(s + kpr.*M.*xi.^2))))) + alphad.*eta.*G.*kpz.*ktz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(...
                ((cd.*(2.*betae.*eta.*G.*kptz - alphad.^2.*kpz).*M + alpha.^2.*ktz.*M.*md + 2.*eta.*G.*(ktz - (cd.*kpz + betae.*ktpz).*M).*md + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md)).*s + ...
                  2.*eta.*G.*((-kptz).*ktpr + kptr.*ktpz - kpz.*ktr + kpr.*ktz).*M.*md.*xi.^2).^2 - 4.*M.*((-alphad.^2).*cd.*kptz.*s + alpha.*alphad.*ktz.*md.*s - 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + ...
                    (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s - kpz.*ktpr.*M.*md.*xi.^2 + ktpz.*md.*(s + kpr.*M.*xi.^2)))))))./...
          (4.*eta.*G.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2))))).*...
      ((1./2).*h.*xi.^2.*(1./(1 - v) + (s.*((-cd).*(alphad.^2 + 2.*alpha.*alphad.*betae.*M + alpha.^2.*M.*md).*s + M.*(alphad.*cd.*(alpha.*(kptr - kptz) + alphad.*(-kpr + kpz)) + ...
              alpha.*(alphad.*(ktpr - ktpz) + alpha.*(-ktr + ktz)).*md).*xi.^2))./(eta.*((-cd).*(alphad.^2 + 2.*alpha.*alphad.*betae.*M - 2.*betae.^2.*eta.*G.*M + 2.*eta.*G.*md + alpha.^2.*M.*md).*s.^2 + ...
            (cd.*(alpha.*alphad.*(kptr - kptz) + 2.*betae.*eta.*G.*(-kptr + kptz) + alphad.^2.*(-kpr + kpz)).*M + (alpha.*(alphad.*(ktpr - ktpz) + alpha.*(-ktr + ktz)).*M + ...
                2.*eta.*G.*(-ktr + ktz + cd.*(-kpr + kpz).*M + betae.*(-ktpr + ktpz).*M)).*md).*s.*xi.^2 + 2.*eta.*G.*((kptr - kptz).*(ktpr - ktpz) - (kpr - kpz).*(ktr - ktz)).*M.*md.*xi.^4))) + ...
       (-xi + (1./2).*xi.*(1./(1 - v) + (s.*((-cd).*(alphad.^2 + 2.*alpha.*alphad.*betae.*M + alpha.^2.*M.*md).*s + M.*(alphad.*cd.*(alpha.*(kptr - kptz) + alphad.*(-kpr + kpz)) + ...
                alpha.*(alphad.*(ktpr - ktpz) + alpha.*(-ktr + ktz)).*md).*xi.^2))./(eta.*((-cd).*(alphad.^2 + 2.*alpha.*alphad.*betae.*M - 2.*betae.^2.*eta.*G.*M + 2.*eta.*G.*md + alpha.^2.*M.*md).*s.^2 + ...
              (cd.*(alpha.*alphad.*(kptr - kptz) + 2.*betae.*eta.*G.*(-kptr + kptz) + alphad.^2.*(-kpr + kpz)).*M + (alpha.*(alphad.*(ktpr - ktpz) + alpha.*(-ktr + ktz)).*M + ...
                  2.*eta.*G.*(-ktr + ktz + cd.*(-kpr + kpz).*M + betae.*(-ktpr + ktpz).*M)).*md).*s.*xi.^2 + 2.*eta.*G.*((kptr - kptz).*(ktpr - ktpz) - (kpr - kpz).*(ktr - ktz)).*M.*md.*xi.^4)))).*tanh(h.*xi)) + ...
     (xi.*sqrt((alpha.*alphad.*s - 2.*betae.*eta.*G.*s + 2.*eta.*G.*kptr.*xi.^2)./(eta.*G.*kptz) + (1./(eta.*G.*kptz.*(kptz.*ktpz - kpz.*ktz).*M.*md)).*...
          ((-(cd.*kptz.*((-alpha).*alphad.*kptz + 2.*betae.*eta.*G.*kptz + alphad.^2.*kpz).*M + alpha.*(alpha.*kptz - alphad.*kpz).*ktz.*M.*md + 2.*eta.*G.*(betae.*kpz.*ktz.*M + kptz.*(ktz + cd.*kpz.*M)).*md)).*s + ...
           2.*eta.*G.*(kptz.^2.*ktpr + kptr.*kpz.*ktz - kptz.*(kpz.*ktr + kpr.*ktz)).*M.*md.*xi.^2) - sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*...
           (((cd.*(2.*betae.*eta.*G.*kptz - alphad.^2.*kpz).*M + alpha.^2.*ktz.*M.*md + 2.*eta.*G.*(ktz - (cd.*kpz + betae.*ktpz).*M).*md + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md)).*s + ...
              2.*eta.*G.*((-kptz).*ktpr + kptr.*ktpz - kpz.*ktr + kpr.*ktz).*M.*md.*xi.^2).^2 - 4.*M.*((-alphad.^2).*cd.*kptz.*s + alpha.*alphad.*ktz.*md.*s - 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + ...
                (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s - kpz.*ktpr.*M.*md.*xi.^2 + ktpz.*md.*(s + kpr.*M.*xi.^2)))))).*...
       ((alphad.^3.*cd.*kpz.*M + alpha.^2.*alphad.*ktz.*M.*md + 2.*alphad.*eta.*G.*((-betae).*cd.*kptz.*M - ktz.*md + cd.*kpz.*M.*md + betae.*ktpz.*M.*md) - ...
          alpha.*M.*(4.*eta.*G.*(cd.*kptz + betae.*ktz).*md + alphad.^2.*(cd.*kptz + ktpz.*md))).*s + 2.*eta.*G.*(alphad.*(kptz.*ktpr - kptr.*ktpz + kpz.*ktr - kpr.*ktz) + alpha.*(-2.*kptz.*ktr + 2.*kptr.*ktz)).*M.*md.*xi.^2 + ...
        alphad.*eta.*G.*kptz.*ktpz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((cd.*(2.*betae.*eta.*G.*kptz - alphad.^2.*kpz).*M + alpha.^2.*ktz.*M.*md + 2.*eta.*G.*(ktz - (cd.*kpz + betae.*ktpz).*M).*...
                 md + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md)).*s + 2.*eta.*G.*((-kptz).*ktpr + kptr.*ktpz - kpz.*ktr + kpr.*ktz).*M.*md.*xi.^2).^2 - ...
            4.*M.*((-alphad.^2).*cd.*kptz.*s + alpha.*alphad.*ktz.*md.*s - 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + ...
              2.*eta.*G.*(betae.*cd.*kpz.*M.*s - kpz.*ktpr.*M.*md.*xi.^2 + ktpz.*md.*(s + kpr.*M.*xi.^2))))) - alphad.*eta.*G.*kpz.*ktz.*M.*md.*...
         sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((cd.*(2.*betae.*eta.*G.*kptz - alphad.^2.*kpz).*M + alpha.^2.*ktz.*M.*md + 2.*eta.*G.*(ktz - (cd.*kpz + betae.*ktpz).*M).*md + ...
                alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md)).*s + 2.*eta.*G.*((-kptz).*ktpr + kptr.*ktpz - kpz.*ktr + kpr.*ktz).*M.*md.*xi.^2).^2 - 4.*M.*((-alphad.^2).*cd.*kptz.*s + alpha.*alphad.*ktz.*md.*s - ...
              2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s - kpz.*ktpr.*M.*md.*xi.^2 + ...
                ktpz.*md.*(s + kpr.*M.*xi.^2)))))).*(xi.^2 + (1./4).*(-((alpha.*alphad.*s - 2.*betae.*eta.*G.*s + 2.*eta.*G.*kptr.*xi.^2)./(eta.*G.*kptz)) - (1./(eta.*G.*kptz.*(kptz.*ktpz - kpz.*ktz).*M.*md)).*...
           ((-(cd.*kptz.*((-alpha).*alphad.*kptz + 2.*betae.*eta.*G.*kptz + alphad.^2.*kpz).*M + alpha.*(alpha.*kptz - alphad.*kpz).*ktz.*M.*md + 2.*eta.*G.*(betae.*kpz.*ktz.*M + kptz.*(ktz + cd.*kpz.*M)).*md)).*s + ...
            2.*eta.*G.*(kptz.^2.*ktpr + kptr.*kpz.*ktz - kptz.*(kpz.*ktr + kpr.*ktz)).*M.*md.*xi.^2) - sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*...
            (((cd.*(2.*betae.*eta.*G.*kptz - alphad.^2.*kpz).*M + alpha.^2.*ktz.*M.*md + 2.*eta.*G.*(ktz - (cd.*kpz + betae.*ktpz).*M).*md + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md)).*s + 2.*eta.*G.*...
                ((-kptz).*ktpr + kptr.*ktpz - kpz.*ktr + kpr.*ktz).*M.*md.*xi.^2).^2 - 4.*M.*((-alphad.^2).*cd.*kptz.*s + alpha.*alphad.*ktz.*md.*s - 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + ...
                 (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s - kpz.*ktpr.*M.*md.*xi.^2 + ktpz.*md.*(s + kpr.*M.*xi.^2)))))) - ...
        (s.*xi.^2.*((-cd).*(alphad.*betae + alpha.*md).*s + (alphad.*cd.*(kptr - kptz) + alpha.*(-ktr + ktz).*md).*xi.^2).*...
          ((alphad.^3.*cd.*kpz.*M + alpha.^2.*alphad.*ktz.*M.*md + 2.*alphad.*eta.*G.*((-betae).*cd.*kptz.*M - ktz.*md + cd.*kpz.*M.*md + betae.*ktpz.*M.*md) - ...
             alpha.*M.*(4.*eta.*G.*(cd.*kptz + betae.*ktz).*md + alphad.^2.*(cd.*kptz + ktpz.*md))).*s + 2.*eta.*G.*(alphad.*(kptz.*ktpr - kptr.*ktpz + kpz.*ktr - kpr.*ktz) + alpha.*(-2.*kptz.*ktr + 2.*kptr.*ktz)).*M.*md.*...
            xi.^2 - alphad.*eta.*G.*kptz.*ktpz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((cd.*(2.*betae.*eta.*G.*kptz - alphad.^2.*kpz).*M + alpha.^2.*ktz.*M.*md + ...
                   2.*eta.*G.*(ktz - (cd.*kpz + betae.*ktpz).*M).*md + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md)).*s + 2.*eta.*G.*((-kptz).*ktpr + kptr.*ktpz - kpz.*ktr + kpr.*ktz).*M.*md.*xi.^2).^2 - 4.*M.*...
                ((-alphad.^2).*cd.*kptz.*s + alpha.*alphad.*ktz.*md.*s - 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + ...
                 2.*eta.*G.*(betae.*cd.*kpz.*M.*s - kpz.*ktpr.*M.*md.*xi.^2 + ktpz.*md.*(s + kpr.*M.*xi.^2))))) + alphad.*eta.*G.*kpz.*ktz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*...
              (((cd.*(2.*betae.*eta.*G.*kptz - alphad.^2.*kpz).*M + alpha.^2.*ktz.*M.*md + 2.*eta.*G.*(ktz - (cd.*kpz + betae.*ktpz).*M).*md + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md)).*s + ...
                 2.*eta.*G.*((-kptz).*ktpr + kptr.*ktpz - kpz.*ktr + kpr.*ktz).*M.*md.*xi.^2).^2 - 4.*M.*((-alphad.^2).*cd.*kptz.*s + alpha.*alphad.*ktz.*md.*s - 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + ...
                   (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s - kpz.*ktpr.*M.*md.*xi.^2 + ktpz.*md.*(s + kpr.*M.*xi.^2)))))))./...
         (2.*eta.*(cd.*(alphad.^2 + 2.*alpha.*alphad.*betae.*M - 2.*betae.^2.*eta.*G.*M + 2.*eta.*G.*md + alpha.^2.*M.*md).*s.^2 + (cd.*(2.*betae.*eta.*G.*(kptr - kptz) + alpha.*alphad.*(-kptr + kptz) + alphad.^2.*(kpr - kpz)).*...
              M + (alpha.*(alphad.*(-ktpr + ktpz) + alpha.*(ktr - ktz)).*M + 2.*eta.*G.*(ktr - ktz + cd.*(kpr - kpz).*M + betae.*(ktpr - ktpz).*M)).*md).*s.*xi.^2 + ...
           2.*eta.*G.*((-(kptr - kptz)).*(ktpr - ktpz) + (kpr - kpz).*(ktr - ktz)).*M.*md.*xi.^4).*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + ...
           2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2))) + ...
        (1./2).*h.*xi.*(1./(1 - v) + (s.*((-cd).*(alphad.^2 + 2.*alpha.*alphad.*betae.*M + alpha.^2.*M.*md).*s + M.*(alphad.*cd.*(alpha.*(kptr - kptz) + alphad.*(-kpr + kpz)) + alpha.*(alphad.*(ktpr - ktpz) + ...
                 alpha.*(-ktr + ktz)).*md).*xi.^2))./(eta.*((-cd).*(alphad.^2 + 2.*alpha.*alphad.*betae.*M - 2.*betae.^2.*eta.*G.*M + 2.*eta.*G.*md + alpha.^2.*M.*md).*s.^2 + ...
             (cd.*(alpha.*alphad.*(kptr - kptz) + 2.*betae.*eta.*G.*(-kptr + kptz) + alphad.^2.*(-kpr + kpz)).*M + (alpha.*(alphad.*(ktpr - ktpz) + alpha.*(-ktr + ktz)).*M + ...
                 2.*eta.*G.*(-ktr + ktz + cd.*(-kpr + kpz).*M + betae.*(-ktpr + ktpz).*M)).*md).*s.*xi.^2 + 2.*eta.*G.*((kptr - kptz).*(ktpr - ktpz) - (kpr - kpz).*(ktr - ktz)).*M.*md.*xi.^4))).*...
         (-xi.^2 + (1./4).*((alpha.*alphad.*s - 2.*betae.*eta.*G.*s + 2.*eta.*G.*kptr.*xi.^2)./(eta.*G.*kptz) + (1./(eta.*G.*kptz.*(kptz.*ktpz - kpz.*ktz).*M.*md)).*...
             ((-(cd.*kptz.*((-alpha).*alphad.*kptz + 2.*betae.*eta.*G.*kptz + alphad.^2.*kpz).*M + alpha.*(alpha.*kptz - alphad.*kpz).*ktz.*M.*md + 2.*eta.*G.*(betae.*kpz.*ktz.*M + kptz.*(ktz + cd.*kpz.*M)).*md)).*s + ...
              2.*eta.*G.*(kptz.^2.*ktpr + kptr.*kpz.*ktz - kptz.*(kpz.*ktr + kpr.*ktz)).*M.*md.*xi.^2) + sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*...
              (((cd.*(2.*betae.*eta.*G.*kptz - alphad.^2.*kpz).*M + alpha.^2.*ktz.*M.*md + 2.*eta.*G.*(ktz - (cd.*kpz + betae.*ktpz).*M).*md + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md)).*s + ...
                 2.*eta.*G.*((-kptz).*ktpr + kptr.*ktpz - kpz.*ktr + kpr.*ktz).*M.*md.*xi.^2).^2 - 4.*M.*((-alphad.^2).*cd.*kptz.*s + alpha.*alphad.*ktz.*md.*s - 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + ...
                   (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s - kpz.*ktpr.*M.*md.*xi.^2 + ktpz.*md.*(s + kpr.*M.*xi.^2))))))).*tanh(h.*xi)).*...
       tanh((1./2).*h.*sqrt((alpha.*alphad.*s - 2.*betae.*eta.*G.*s + 2.*eta.*G.*kptr.*xi.^2)./(eta.*G.*kptz) + (1./(eta.*G.*kptz.*(kptz.*ktpz - kpz.*ktz).*M.*md)).*...
            ((-(cd.*kptz.*((-alpha).*alphad.*kptz + 2.*betae.*eta.*G.*kptz + alphad.^2.*kpz).*M + alpha.*(alpha.*kptz - alphad.*kpz).*ktz.*M.*md + 2.*eta.*G.*(betae.*kpz.*ktz.*M + kptz.*(ktz + cd.*kpz.*M)).*md)).*s + ...
             2.*eta.*G.*(kptz.^2.*ktpr + kptr.*kpz.*ktz - kptz.*(kpz.*ktr + kpr.*ktz)).*M.*md.*xi.^2) - sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*...
             (((cd.*(2.*betae.*eta.*G.*kptz - alphad.^2.*kpz).*M + alpha.^2.*ktz.*M.*md + 2.*eta.*G.*(ktz - (cd.*kpz + betae.*ktpz).*M).*md + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md)).*s + ...
                2.*eta.*G.*((-kptz).*ktpr + kptr.*ktpz - kpz.*ktr + kpr.*ktz).*M.*md.*xi.^2).^2 - 4.*M.*((-alphad.^2).*cd.*kptz.*s + alpha.*alphad.*ktz.*md.*s - 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + ...
                  (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s - kpz.*ktpr.*M.*md.*xi.^2 + ktpz.*md.*(s + kpr.*M.*xi.^2))))))))./...
      (8.*eta.*G.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2))) + ...
     (xi.*sqrt((alpha.*alphad.*s - 2.*betae.*eta.*G.*s + 2.*eta.*G.*kptr.*xi.^2)./(eta.*G.*kptz) + (1./(eta.*G.*kptz.*(kptz.*ktpz - kpz.*ktz).*M.*md)).*...
          ((-(cd.*kptz.*((-alpha).*alphad.*kptz + 2.*betae.*eta.*G.*kptz + alphad.^2.*kpz).*M + alpha.*(alpha.*kptz - alphad.*kpz).*ktz.*M.*md + 2.*eta.*G.*(betae.*kpz.*ktz.*M + kptz.*(ktz + cd.*kpz.*M)).*md)).*s + ...
           2.*eta.*G.*(kptz.^2.*ktpr + kptr.*kpz.*ktz - kptz.*(kpz.*ktr + kpr.*ktz)).*M.*md.*xi.^2) + sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*...
           (((cd.*(2.*betae.*eta.*G.*kptz - alphad.^2.*kpz).*M + alpha.^2.*ktz.*M.*md + 2.*eta.*G.*(ktz - (cd.*kpz + betae.*ktpz).*M).*md + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md)).*s + ...
              2.*eta.*G.*((-kptz).*ktpr + kptr.*ktpz - kpz.*ktr + kpr.*ktz).*M.*md.*xi.^2).^2 - 4.*M.*((-alphad.^2).*cd.*kptz.*s + alpha.*alphad.*ktz.*md.*s - 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + ...
                (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s - kpz.*ktpr.*M.*md.*xi.^2 + ktpz.*md.*(s + kpr.*M.*xi.^2)))))).*...
       ((alphad.^3.*cd.*kpz.*M + alpha.^2.*alphad.*ktz.*M.*md + 2.*alphad.*eta.*G.*((-betae).*cd.*kptz.*M - ktz.*md + cd.*kpz.*M.*md + betae.*ktpz.*M.*md) - ...
          alpha.*M.*(4.*eta.*G.*(cd.*kptz + betae.*ktz).*md + alphad.^2.*(cd.*kptz + ktpz.*md))).*s + 2.*eta.*G.*(alphad.*(kptz.*ktpr - kptr.*ktpz + kpz.*ktr - kpr.*ktz) + alpha.*(-2.*kptz.*ktr + 2.*kptr.*ktz)).*M.*md.*xi.^2 - ...
        alphad.*eta.*G.*kptz.*ktpz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((cd.*(2.*betae.*eta.*G.*kptz - alphad.^2.*kpz).*M + alpha.^2.*ktz.*M.*md + 2.*eta.*G.*(ktz - (cd.*kpz + betae.*ktpz).*M).*...
                 md + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md)).*s + 2.*eta.*G.*((-kptz).*ktpr + kptr.*ktpz - kpz.*ktr + kpr.*ktz).*M.*md.*xi.^2).^2 - ...
            4.*M.*((-alphad.^2).*cd.*kptz.*s + alpha.*alphad.*ktz.*md.*s - 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + ...
              2.*eta.*G.*(betae.*cd.*kpz.*M.*s - kpz.*ktpr.*M.*md.*xi.^2 + ktpz.*md.*(s + kpr.*M.*xi.^2))))) + alphad.*eta.*G.*kpz.*ktz.*M.*md.*...
         sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((cd.*(2.*betae.*eta.*G.*kptz - alphad.^2.*kpz).*M + alpha.^2.*ktz.*M.*md + 2.*eta.*G.*(ktz - (cd.*kpz + betae.*ktpz).*M).*md + ...
                alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md)).*s + 2.*eta.*G.*((-kptz).*ktpr + kptr.*ktpz - kpz.*ktr + kpr.*ktz).*M.*md.*xi.^2).^2 - 4.*M.*((-alphad.^2).*cd.*kptz.*s + alpha.*alphad.*ktz.*md.*s - ...
              2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s - kpz.*ktpr.*M.*md.*xi.^2 + ...
                ktpz.*md.*(s + kpr.*M.*xi.^2)))))).*(-xi.^2 + (1./4).*((alpha.*alphad.*s - 2.*betae.*eta.*G.*s + 2.*eta.*G.*kptr.*xi.^2)./(eta.*G.*kptz) + (1./(eta.*G.*kptz.*(kptz.*ktpz - kpz.*ktz).*M.*md)).*...
           ((-(cd.*kptz.*((-alpha).*alphad.*kptz + 2.*betae.*eta.*G.*kptz + alphad.^2.*kpz).*M + alpha.*(alpha.*kptz - alphad.*kpz).*ktz.*M.*md + 2.*eta.*G.*(betae.*kpz.*ktz.*M + kptz.*(ktz + cd.*kpz.*M)).*md)).*s + ...
            2.*eta.*G.*(kptz.^2.*ktpr + kptr.*kpz.*ktz - kptz.*(kpz.*ktr + kpr.*ktz)).*M.*md.*xi.^2) - sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*...
            (((cd.*(2.*betae.*eta.*G.*kptz - alphad.^2.*kpz).*M + alpha.^2.*ktz.*M.*md + 2.*eta.*G.*(ktz - (cd.*kpz + betae.*ktpz).*M).*md + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md)).*s + 2.*eta.*G.*...
                ((-kptz).*ktpr + kptr.*ktpz - kpz.*ktr + kpr.*ktz).*M.*md.*xi.^2).^2 - 4.*M.*((-alphad.^2).*cd.*kptz.*s + alpha.*alphad.*ktz.*md.*s - 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + ...
                 (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s - kpz.*ktpr.*M.*md.*xi.^2 + ktpz.*md.*(s + kpr.*M.*xi.^2)))))) + ...
        (s.*xi.^2.*((-cd).*(alphad.*betae + alpha.*md).*s + (alphad.*cd.*(kptr - kptz) + alpha.*(-ktr + ktz).*md).*xi.^2).*...
          ((alphad.^3.*cd.*kpz.*M + alpha.^2.*alphad.*ktz.*M.*md + 2.*alphad.*eta.*G.*((-betae).*cd.*kptz.*M - ktz.*md + cd.*kpz.*M.*md + betae.*ktpz.*M.*md) - ...
             alpha.*M.*(4.*eta.*G.*(cd.*kptz + betae.*ktz).*md + alphad.^2.*(cd.*kptz + ktpz.*md))).*s + 2.*eta.*G.*(alphad.*(kptz.*ktpr - kptr.*ktpz + kpz.*ktr - kpr.*ktz) + alpha.*(-2.*kptz.*ktr + 2.*kptr.*ktz)).*M.*md.*...
            xi.^2 + alphad.*eta.*G.*kptz.*ktpz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((cd.*(2.*betae.*eta.*G.*kptz - alphad.^2.*kpz).*M + alpha.^2.*ktz.*M.*md + ...
                   2.*eta.*G.*(ktz - (cd.*kpz + betae.*ktpz).*M).*md + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md)).*s + 2.*eta.*G.*((-kptz).*ktpr + kptr.*ktpz - kpz.*ktr + kpr.*ktz).*M.*md.*xi.^2).^2 - 4.*M.*...
                ((-alphad.^2).*cd.*kptz.*s + alpha.*alphad.*ktz.*md.*s - 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + ...
                 2.*eta.*G.*(betae.*cd.*kpz.*M.*s - kpz.*ktpr.*M.*md.*xi.^2 + ktpz.*md.*(s + kpr.*M.*xi.^2))))) - alphad.*eta.*G.*kpz.*ktz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*...
              (((cd.*(2.*betae.*eta.*G.*kptz - alphad.^2.*kpz).*M + alpha.^2.*ktz.*M.*md + 2.*eta.*G.*(ktz - (cd.*kpz + betae.*ktpz).*M).*md + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md)).*s + ...
                 2.*eta.*G.*((-kptz).*ktpr + kptr.*ktpz - kpz.*ktr + kpr.*ktz).*M.*md.*xi.^2).^2 - 4.*M.*((-alphad.^2).*cd.*kptz.*s + alpha.*alphad.*ktz.*md.*s - 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + ...
                   (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s - kpz.*ktpr.*M.*md.*xi.^2 + ktpz.*md.*(s + kpr.*M.*xi.^2)))))))./...
         (2.*eta.*(cd.*(alphad.^2 + 2.*alpha.*alphad.*betae.*M - 2.*betae.^2.*eta.*G.*M + 2.*eta.*G.*md + alpha.^2.*M.*md).*s.^2 + (cd.*(2.*betae.*eta.*G.*(kptr - kptz) + alpha.*alphad.*(-kptr + kptz) + alphad.^2.*(kpr - kpz)).*...
              M + (alpha.*(alphad.*(-ktpr + ktpz) + alpha.*(ktr - ktz)).*M + 2.*eta.*G.*(ktr - ktz + cd.*(kpr - kpz).*M + betae.*(ktpr - ktpz).*M)).*md).*s.*xi.^2 + ...
           2.*eta.*G.*((-(kptr - kptz)).*(ktpr - ktpz) + (kpr - kpz).*(ktr - ktz)).*M.*md.*xi.^4).*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + ...
           2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2))) + ...
        (1./2).*h.*xi.*(1./(1 - v) + (s.*((-cd).*(alphad.^2 + 2.*alpha.*alphad.*betae.*M + alpha.^2.*M.*md).*s + M.*(alphad.*cd.*(alpha.*(kptr - kptz) + alphad.*(-kpr + kpz)) + alpha.*(alphad.*(ktpr - ktpz) + ...
                 alpha.*(-ktr + ktz)).*md).*xi.^2))./(eta.*((-cd).*(alphad.^2 + 2.*alpha.*alphad.*betae.*M - 2.*betae.^2.*eta.*G.*M + 2.*eta.*G.*md + alpha.^2.*M.*md).*s.^2 + ...
             (cd.*(alpha.*alphad.*(kptr - kptz) + 2.*betae.*eta.*G.*(-kptr + kptz) + alphad.^2.*(-kpr + kpz)).*M + (alpha.*(alphad.*(ktpr - ktpz) + alpha.*(-ktr + ktz)).*M + ...
                 2.*eta.*G.*(-ktr + ktz + cd.*(-kpr + kpz).*M + betae.*(-ktpr + ktpz).*M)).*md).*s.*xi.^2 + 2.*eta.*G.*((kptr - kptz).*(ktpr - ktpz) - (kpr - kpz).*(ktr - ktz)).*M.*md.*xi.^4))).*...
         (xi.^2 + (1./4).*(-((alpha.*alphad.*s - 2.*betae.*eta.*G.*s + 2.*eta.*G.*kptr.*xi.^2)./(eta.*G.*kptz)) - (1./(eta.*G.*kptz.*(kptz.*ktpz - kpz.*ktz).*M.*md)).*...
             ((-(cd.*kptz.*((-alpha).*alphad.*kptz + 2.*betae.*eta.*G.*kptz + alphad.^2.*kpz).*M + alpha.*(alpha.*kptz - alphad.*kpz).*ktz.*M.*md + 2.*eta.*G.*(betae.*kpz.*ktz.*M + kptz.*(ktz + cd.*kpz.*M)).*md)).*s + ...
              2.*eta.*G.*(kptz.^2.*ktpr + kptr.*kpz.*ktz - kptz.*(kpz.*ktr + kpr.*ktz)).*M.*md.*xi.^2) + sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*...
              (((cd.*(2.*betae.*eta.*G.*kptz - alphad.^2.*kpz).*M + alpha.^2.*ktz.*M.*md + 2.*eta.*G.*(ktz - (cd.*kpz + betae.*ktpz).*M).*md + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md)).*s + ...
                 2.*eta.*G.*((-kptz).*ktpr + kptr.*ktpz - kpz.*ktr + kpr.*ktz).*M.*md.*xi.^2).^2 - 4.*M.*((-alphad.^2).*cd.*kptz.*s + alpha.*alphad.*ktz.*md.*s - 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + ...
                   (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s - kpz.*ktpr.*M.*md.*xi.^2 + ktpz.*md.*(s + kpr.*M.*xi.^2))))))).*tanh(h.*xi)).*...
       tanh((1./2).*h.*sqrt((alpha.*alphad.*s - 2.*betae.*eta.*G.*s + 2.*eta.*G.*kptr.*xi.^2)./(eta.*G.*kptz) + (1./(eta.*G.*kptz.*(kptz.*ktpz - kpz.*ktz).*M.*md)).*...
            ((-(cd.*kptz.*((-alpha).*alphad.*kptz + 2.*betae.*eta.*G.*kptz + alphad.^2.*kpz).*M + alpha.*(alpha.*kptz - alphad.*kpz).*ktz.*M.*md + 2.*eta.*G.*(betae.*kpz.*ktz.*M + kptz.*(ktz + cd.*kpz.*M)).*md)).*s + ...
             2.*eta.*G.*(kptz.^2.*ktpr + kptr.*kpz.*ktz - kptz.*(kpz.*ktr + kpr.*ktz)).*M.*md.*xi.^2) + sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*...
             (((cd.*(2.*betae.*eta.*G.*kptz - alphad.^2.*kpz).*M + alpha.^2.*ktz.*M.*md + 2.*eta.*G.*(ktz - (cd.*kpz + betae.*ktpz).*M).*md + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md)).*s + ...
                2.*eta.*G.*((-kptz).*ktpr + kptr.*ktpz - kpz.*ktr + kpr.*ktz).*M.*md.*xi.^2).^2 - 4.*M.*((-alphad.^2).*cd.*kptz.*s + alpha.*alphad.*ktz.*md.*s - 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + ...
                  (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s - kpz.*ktpr.*M.*md.*xi.^2 + ktpz.*md.*(s + kpr.*M.*xi.^2))))))))./...
      (8.*eta.*G.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)))))./...
   (2.*G.*s.*xi.*((1./(2.*G)).*(h.*xi.^2.*(1./(1 - v) + (s.*((-cd).*(alphad.^2 + 2.*alpha.*alphad.*betae.*M + alpha.^2.*M.*md).*s + M.*(alphad.*cd.*(alpha.*(kptr - kptz) + alphad.*(-kpr + kpz)) + ...
             alpha.*(alphad.*(ktpr - ktpz) + alpha.*(-ktr + ktz)).*md).*xi.^2))./(eta.*((-cd).*(alphad.^2 + 2.*alpha.*alphad.*betae.*M - 2.*betae.^2.*eta.*G.*M + 2.*eta.*G.*md + alpha.^2.*M.*md).*s.^2 + ...
           (cd.*(alpha.*alphad.*(kptr - kptz) + 2.*betae.*eta.*G.*(-kptr + kptz) + alphad.^2.*(-kpr + kpz)).*M + (alpha.*(alphad.*(ktpr - ktpz) + alpha.*(-ktr + ktz)).*M + 2.*eta.*G.*...
                (-ktr + ktz + cd.*(-kpr + kpz).*M + betae.*(-ktpr + ktpz).*M)).*md).*s.*xi.^2 + 2.*eta.*G.*((kptr - kptz).*(ktpr - ktpz) - (kpr - kpz).*(ktr - ktz)).*M.*md.*xi.^4))).*...
       (-xi.^2 + (1./4).*((alpha.*alphad.*s - 2.*betae.*eta.*G.*s + 2.*eta.*G.*kptr.*xi.^2)./(eta.*G.*kptz) + (1./(eta.*G.*kptz.*(kptz.*ktpz - kpz.*ktz).*M.*md)).*...
           ((-(cd.*kptz.*((-alpha).*alphad.*kptz + 2.*betae.*eta.*G.*kptz + alphad.^2.*kpz).*M + alpha.*(alpha.*kptz - alphad.*kpz).*ktz.*M.*md + 2.*eta.*G.*(betae.*kpz.*ktz.*M + kptz.*(ktz + cd.*kpz.*M)).*md)).*s + ...
            2.*eta.*G.*(kptz.^2.*ktpr + kptr.*kpz.*ktz - kptz.*(kpz.*ktr + kpr.*ktz)).*M.*md.*xi.^2) - sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*...
            (((cd.*(2.*betae.*eta.*G.*kptz - alphad.^2.*kpz).*M + alpha.^2.*ktz.*M.*md + 2.*eta.*G.*(ktz - (cd.*kpz + betae.*ktpz).*M).*md + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md)).*s + 2.*eta.*G.*...
                ((-kptz).*ktpr + kptr.*ktpz - kpz.*ktr + kpr.*ktz).*M.*md.*xi.^2).^2 - 4.*M.*((-alphad.^2).*cd.*kptz.*s + alpha.*alphad.*ktz.*md.*s - 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + ...
                 (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s - kpz.*ktpr.*M.*md.*xi.^2 + ktpz.*md.*(s + kpr.*M.*xi.^2))))))).*...
       (-xi.^2 + (1./4).*((alpha.*alphad.*s - 2.*betae.*eta.*G.*s + 2.*eta.*G.*kptr.*xi.^2)./(eta.*G.*kptz) + (1./(eta.*G.*kptz.*(kptz.*ktpz - kpz.*ktz).*M.*md)).*...
           ((-(cd.*kptz.*((-alpha).*alphad.*kptz + 2.*betae.*eta.*G.*kptz + alphad.^2.*kpz).*M + alpha.*(alpha.*kptz - alphad.*kpz).*ktz.*M.*md + 2.*eta.*G.*(betae.*kpz.*ktz.*M + kptz.*(ktz + cd.*kpz.*M)).*md)).*s + ...
            2.*eta.*G.*(kptz.^2.*ktpr + kptr.*kpz.*ktz - kptz.*(kpz.*ktr + kpr.*ktz)).*M.*md.*xi.^2) + sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*...
            (((cd.*(2.*betae.*eta.*G.*kptz - alphad.^2.*kpz).*M + alpha.^2.*ktz.*M.*md + 2.*eta.*G.*(ktz - (cd.*kpz + betae.*ktpz).*M).*md + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md)).*s + 2.*eta.*G.*...
                ((-kptz).*ktpr + kptr.*ktpz - kpz.*ktr + kpr.*ktz).*M.*md.*xi.^2).^2 - 4.*M.*((-alphad.^2).*cd.*kptz.*s + alpha.*alphad.*ktz.*md.*s - 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + ...
                 (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s - kpz.*ktpr.*M.*md.*xi.^2 + ktpz.*md.*(s + kpr.*M.*xi.^2))))))).*...
       (((-alpha).*alphad.*cd.*kptz.*M.*s + 2.*betae.*cd.*eta.*G.*kptz.*M.*s - alphad.^2.*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + alpha.*alphad.*ktpz.*M.*md.*s - 2.*betae.*eta.*G.*ktpz.*M.*md.*s + ...
          alpha.^2.*ktz.*M.*md.*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2 + ...
          eta.*G.*kptz.*ktpz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((cd.*(2.*betae.*eta.*G.*kptz - alphad.^2.*kpz).*M + alpha.^2.*ktz.*M.*md + 2.*eta.*G.*(ktz - (cd.*kpz + betae.*ktpz).*M).*md + ...
                  alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md)).*s + 2.*eta.*G.*((-kptz).*ktpr + kptr.*ktpz - kpz.*ktr + kpr.*ktz).*M.*md.*xi.^2).^2 - 4.*M.*((-alphad.^2).*cd.*kptz.*s + alpha.*alphad.*ktz.*md.*s - ...
                2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s - kpz.*ktpr.*M.*md.*xi.^2 + ...
                  ktpz.*md.*(s + kpr.*M.*xi.^2))))) - eta.*G.*kpz.*ktz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*...
             (((cd.*(2.*betae.*eta.*G.*kptz - alphad.^2.*kpz).*M + alpha.^2.*ktz.*M.*md + 2.*eta.*G.*(ktz - (cd.*kpz + betae.*ktpz).*M).*md + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md)).*s + ...
                2.*eta.*G.*((-kptz).*ktpr + kptr.*ktpz - kpz.*ktr + kpr.*ktz).*M.*md.*xi.^2).^2 - 4.*M.*((-alphad.^2).*cd.*kptz.*s + alpha.*alphad.*ktz.*md.*s - 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + ...
                  (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s - kpz.*ktpr.*M.*md.*xi.^2 + ktpz.*md.*(s + kpr.*M.*xi.^2))))))./...
         (2.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2))) - ...
        ((-alpha).*alphad.*cd.*kptz.*M.*s + 2.*betae.*cd.*eta.*G.*kptz.*M.*s - alphad.^2.*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + alpha.*alphad.*ktpz.*M.*md.*s - 2.*betae.*eta.*G.*ktpz.*M.*md.*s + ...
          alpha.^2.*ktz.*M.*md.*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2 - ...
          eta.*G.*kptz.*ktpz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((cd.*(2.*betae.*eta.*G.*kptz - alphad.^2.*kpz).*M + alpha.^2.*ktz.*M.*md + 2.*eta.*G.*(ktz - (cd.*kpz + betae.*ktpz).*M).*md + ...
                  alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md)).*s + 2.*eta.*G.*((-kptz).*ktpr + kptr.*ktpz - kpz.*ktr + kpr.*ktz).*M.*md.*xi.^2).^2 - 4.*M.*((-alphad.^2).*cd.*kptz.*s + alpha.*alphad.*ktz.*md.*s - ...
                2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s - kpz.*ktpr.*M.*md.*xi.^2 + ...
                  ktpz.*md.*(s + kpr.*M.*xi.^2))))) + eta.*G.*kpz.*ktz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*...
             (((cd.*(2.*betae.*eta.*G.*kptz - alphad.^2.*kpz).*M + alpha.^2.*ktz.*M.*md + 2.*eta.*G.*(ktz - (cd.*kpz + betae.*ktpz).*M).*md + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md)).*s + ...
                2.*eta.*G.*((-kptz).*ktpr + kptr.*ktpz - kpz.*ktr + kpr.*ktz).*M.*md.*xi.^2).^2 - 4.*M.*((-alphad.^2).*cd.*kptz.*s + alpha.*alphad.*ktz.*md.*s - 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + ...
                  (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s - kpz.*ktpr.*M.*md.*xi.^2 + ktpz.*md.*(s + kpr.*M.*xi.^2))))))./...
         (2.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)))).*sech(h.*xi).^2) + ...
     (-((xi.^3.*((alphad.^3.*cd.*kpz.*M + alpha.^2.*alphad.*ktz.*M.*md + 2.*alphad.*eta.*G.*((-betae).*cd.*kptz.*M - ktz.*md + cd.*kpz.*M.*md + betae.*ktpz.*M.*md) - ...
             alpha.*M.*(4.*eta.*G.*(cd.*kptz + betae.*ktz).*md + alphad.^2.*(cd.*kptz + ktpz.*md))).*s + 2.*eta.*G.*(alphad.*(kptz.*ktpr - kptr.*ktpz + kpz.*ktr - kpr.*ktz) + alpha.*(-2.*kptz.*ktr + 2.*kptr.*ktz)).*M.*md.*...
            xi.^2 + alphad.*eta.*G.*kptz.*ktpz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((cd.*(2.*betae.*eta.*G.*kptz - alphad.^2.*kpz).*M + alpha.^2.*ktz.*M.*md + ...
                   2.*eta.*G.*(ktz - (cd.*kpz + betae.*ktpz).*M).*md + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md)).*s + 2.*eta.*G.*((-kptz).*ktpr + kptr.*ktpz - kpz.*ktr + kpr.*ktz).*M.*md.*xi.^2).^2 - 4.*M.*...
                ((-alphad.^2).*cd.*kptz.*s + alpha.*alphad.*ktz.*md.*s - 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + ...
                 2.*eta.*G.*(betae.*cd.*kpz.*M.*s - kpz.*ktpr.*M.*md.*xi.^2 + ktpz.*md.*(s + kpr.*M.*xi.^2))))) - alphad.*eta.*G.*kpz.*ktz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*...
              (((cd.*(2.*betae.*eta.*G.*kptz - alphad.^2.*kpz).*M + alpha.^2.*ktz.*M.*md + 2.*eta.*G.*(ktz - (cd.*kpz + betae.*ktpz).*M).*md + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md)).*s + ...
                 2.*eta.*G.*((-kptz).*ktpr + kptr.*ktpz - kpz.*ktr + kpr.*ktz).*M.*md.*xi.^2).^2 - 4.*M.*((-alphad.^2).*cd.*kptz.*s + alpha.*alphad.*ktz.*md.*s - 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + ...
                   (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s - kpz.*ktpr.*M.*md.*xi.^2 + ktpz.*md.*(s + kpr.*M.*xi.^2)))))).*...
          (-xi.^2 + (1./4).*((alpha.*alphad.*s - 2.*betae.*eta.*G.*s + 2.*eta.*G.*kptr.*xi.^2)./(eta.*G.*kptz) + (1./(eta.*G.*kptz.*(kptz.*ktpz - kpz.*ktz).*M.*md)).*...
              ((-(cd.*kptz.*((-alpha).*alphad.*kptz + 2.*betae.*eta.*G.*kptz + alphad.^2.*kpz).*M + alpha.*(alpha.*kptz - alphad.*kpz).*ktz.*M.*md + 2.*eta.*G.*(betae.*kpz.*ktz.*M + kptz.*(ktz + cd.*kpz.*M)).*md)).*s + 2.*eta.*...
                G.*(kptz.^2.*ktpr + kptr.*kpz.*ktz - kptz.*(kpz.*ktr + kpr.*ktz)).*M.*md.*xi.^2) + sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(...
                ((cd.*(2.*betae.*eta.*G.*kptz - alphad.^2.*kpz).*M + alpha.^2.*ktz.*M.*md + 2.*eta.*G.*(ktz - (cd.*kpz + betae.*ktpz).*M).*md + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md)).*s + ...
                  2.*eta.*G.*((-kptz).*ktpr + kptr.*ktpz - kpz.*ktr + kpr.*ktz).*M.*md.*xi.^2).^2 - 4.*M.*((-alphad.^2).*cd.*kptz.*s + alpha.*alphad.*ktz.*md.*s - 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + ...
                    (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s - kpz.*ktpr.*M.*md.*xi.^2 + ktpz.*md.*(s + kpr.*M.*xi.^2))))))).*...
          ((s.*((-cd).*(alphad + alpha.*betae.*M).*s + M.*(alphad.*cd.*(-kpr + kpz) + alpha.*(ktpr - ktpz).*md).*xi.^2))./(cd.*(alphad.^2 + 2.*alpha.*alphad.*betae.*M - 2.*betae.^2.*eta.*G.*M + 2.*eta.*G.*md + alpha.^2.*M.*md).*...
              s.^2 + (cd.*(2.*betae.*eta.*G.*(kptr - kptz) + alpha.*alphad.*(-kptr + kptz) + alphad.^2.*(kpr - kpz)).*M + (alpha.*(alphad.*(-ktpr + ktpz) + alpha.*(ktr - ktz)).*M + ...
                 2.*eta.*G.*(ktr - ktz + cd.*(kpr - kpz).*M + betae.*(ktpr - ktpz).*M)).*md).*s.*xi.^2 + 2.*eta.*G.*((-(kptr - kptz)).*(ktpr - ktpz) + (kpr - kpz).*(ktr - ktz)).*M.*md.*xi.^4) - ...
           (s.*((-cd).*(alphad.*betae + alpha.*md).*s + (alphad.*cd.*(kptr - kptz) + alpha.*(-ktr + ktz).*md).*xi.^2).*((-alpha).*alphad.*cd.*kptz.*M.*s + 2.*betae.*cd.*eta.*G.*kptz.*M.*s - alphad.^2.*cd.*kpz.*M.*s + ...
              2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + alpha.*alphad.*ktpz.*M.*md.*s - 2.*betae.*eta.*G.*ktpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - ...
              2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2 + eta.*G.*kptz.*ktpz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*...
                 (((cd.*(2.*betae.*eta.*G.*kptz - alphad.^2.*kpz).*M + alpha.^2.*ktz.*M.*md + 2.*eta.*G.*(ktz - (cd.*kpz + betae.*ktpz).*M).*md + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md)).*s + ...
                    2.*eta.*G.*((-kptz).*ktpr + kptr.*ktpz - kpz.*ktr + kpr.*ktz).*M.*md.*xi.^2).^2 - 4.*M.*((-alphad.^2).*cd.*kptz.*s + alpha.*alphad.*ktz.*md.*s - 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + ...
                      (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s - kpz.*ktpr.*M.*md.*xi.^2 + ktpz.*md.*(s + kpr.*M.*xi.^2))))) - ...
              eta.*G.*kpz.*ktz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((cd.*(2.*betae.*eta.*G.*kptz - alphad.^2.*kpz).*M + alpha.^2.*ktz.*M.*md + 2.*eta.*G.*(ktz - (cd.*kpz + betae.*ktpz).*M).*md + ...
                      alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md)).*s + 2.*eta.*G.*((-kptz).*ktpr + kptr.*ktpz - kpz.*ktr + kpr.*ktz).*M.*md.*xi.^2).^2 - 4.*M.*((-alphad.^2).*cd.*kptz.*s + alpha.*alphad.*ktz.*md.*s - ...
                    2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s - kpz.*ktpr.*M.*md.*xi.^2 + ...
                      ktpz.*md.*(s + kpr.*M.*xi.^2)))))))./(2.*(cd.*(alphad.^2 + 2.*alpha.*alphad.*betae.*M - 2.*betae.^2.*eta.*G.*M + 2.*eta.*G.*md + alpha.^2.*M.*md).*s.^2 + ...
              (cd.*(2.*betae.*eta.*G.*(kptr - kptz) + alpha.*alphad.*(-kptr + kptz) + alphad.^2.*(kpr - kpz)).*M + (alpha.*(alphad.*(-ktpr + ktpz) + alpha.*(ktr - ktz)).*M + ...
                  2.*eta.*G.*(ktr - ktz + cd.*(kpr - kpz).*M + betae.*(ktpr - ktpz).*M)).*md).*s.*xi.^2 + 2.*eta.*G.*((-(kptr - kptz)).*(ktpr - ktpz) + (kpr - kpz).*(ktr - ktz)).*M.*md.*xi.^4).*...
             (alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)))))./...
         (2.*eta.*G.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)))) + ...
       (1./(2.*G)).*(xi.*(1./(1 - v) + (s.*((-cd).*(alphad.^2 + 2.*alpha.*alphad.*betae.*M + alpha.^2.*M.*md).*s + M.*(alphad.*cd.*(alpha.*(kptr - kptz) + alphad.*(-kpr + kpz)) + alpha.*...
                (alphad.*(ktpr - ktpz) + alpha.*(-ktr + ktz)).*md).*xi.^2))./(eta.*((-cd).*(alphad.^2 + 2.*alpha.*alphad.*betae.*M - 2.*betae.^2.*eta.*G.*M + 2.*eta.*G.*md + alpha.^2.*M.*md).*s.^2 + ...
             (cd.*(alpha.*alphad.*(kptr - kptz) + 2.*betae.*eta.*G.*(-kptr + kptz) + alphad.^2.*(-kpr + kpz)).*M + (alpha.*(alphad.*(ktpr - ktpz) + alpha.*(-ktr + ktz)).*M + ...
                 2.*eta.*G.*(-ktr + ktz + cd.*(-kpr + kpz).*M + betae.*(-ktpr + ktpz).*M)).*md).*s.*xi.^2 + 2.*eta.*G.*((kptr - kptz).*(ktpr - ktpz) - (kpr - kpz).*(ktr - ktz)).*M.*md.*xi.^4))).*...
         (-xi.^2 + (1./4).*((alpha.*alphad.*s - 2.*betae.*eta.*G.*s + 2.*eta.*G.*kptr.*xi.^2)./(eta.*G.*kptz) + (1./(eta.*G.*kptz.*(kptz.*ktpz - kpz.*ktz).*M.*md)).*...
             ((-(cd.*kptz.*((-alpha).*alphad.*kptz + 2.*betae.*eta.*G.*kptz + alphad.^2.*kpz).*M + alpha.*(alpha.*kptz - alphad.*kpz).*ktz.*M.*md + 2.*eta.*G.*(betae.*kpz.*ktz.*M + kptz.*(ktz + cd.*kpz.*M)).*md)).*s + ...
              2.*eta.*G.*(kptz.^2.*ktpr + kptr.*kpz.*ktz - kptz.*(kpz.*ktr + kpr.*ktz)).*M.*md.*xi.^2) - sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*...
              (((cd.*(2.*betae.*eta.*G.*kptz - alphad.^2.*kpz).*M + alpha.^2.*ktz.*M.*md + 2.*eta.*G.*(ktz - (cd.*kpz + betae.*ktpz).*M).*md + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md)).*s + ...
                 2.*eta.*G.*((-kptz).*ktpr + kptr.*ktpz - kpz.*ktr + kpr.*ktz).*M.*md.*xi.^2).^2 - 4.*M.*((-alphad.^2).*cd.*kptz.*s + alpha.*alphad.*ktz.*md.*s - 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + ...
                   (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s - kpz.*ktpr.*M.*md.*xi.^2 + ktpz.*md.*(s + kpr.*M.*xi.^2))))))).*...
         (-xi.^2 + (1./4).*((alpha.*alphad.*s - 2.*betae.*eta.*G.*s + 2.*eta.*G.*kptr.*xi.^2)./(eta.*G.*kptz) + (1./(eta.*G.*kptz.*(kptz.*ktpz - kpz.*ktz).*M.*md)).*...
             ((-(cd.*kptz.*((-alpha).*alphad.*kptz + 2.*betae.*eta.*G.*kptz + alphad.^2.*kpz).*M + alpha.*(alpha.*kptz - alphad.*kpz).*ktz.*M.*md + 2.*eta.*G.*(betae.*kpz.*ktz.*M + kptz.*(ktz + cd.*kpz.*M)).*md)).*s + ...
              2.*eta.*G.*(kptz.^2.*ktpr + kptr.*kpz.*ktz - kptz.*(kpz.*ktr + kpr.*ktz)).*M.*md.*xi.^2) + sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*...
              (((cd.*(2.*betae.*eta.*G.*kptz - alphad.^2.*kpz).*M + alpha.^2.*ktz.*M.*md + 2.*eta.*G.*(ktz - (cd.*kpz + betae.*ktpz).*M).*md + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md)).*s + ...
                 2.*eta.*G.*((-kptz).*ktpr + kptr.*ktpz - kpz.*ktr + kpr.*ktz).*M.*md.*xi.^2).^2 - 4.*M.*((-alphad.^2).*cd.*kptz.*s + alpha.*alphad.*ktz.*md.*s - 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + ...
                   (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s - kpz.*ktpr.*M.*md.*xi.^2 + ktpz.*md.*(s + kpr.*M.*xi.^2))))))).*...
         (((-alpha).*alphad.*cd.*kptz.*M.*s + 2.*betae.*cd.*eta.*G.*kptz.*M.*s - alphad.^2.*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + alpha.*alphad.*ktpz.*M.*md.*s - 2.*betae.*eta.*G.*ktpz.*M.*md.*s + ...
            alpha.^2.*ktz.*M.*md.*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - 2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2 + ...
            eta.*G.*kptz.*ktpz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((cd.*(2.*betae.*eta.*G.*kptz - alphad.^2.*kpz).*M + alpha.^2.*ktz.*M.*md + 2.*eta.*G.*(ktz - (cd.*kpz + betae.*ktpz).*M).*md + ...
                    alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md)).*s + 2.*eta.*G.*((-kptz).*ktpr + kptr.*ktpz - kpz.*ktr + kpr.*ktz).*M.*md.*xi.^2).^2 - 4.*M.*((-alphad.^2).*cd.*kptz.*s + alpha.*alphad.*ktz.*md.*s - ...
                  2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s - kpz.*ktpr.*M.*md.*xi.^2 + ...
                    ktpz.*md.*(s + kpr.*M.*xi.^2))))) - eta.*G.*kpz.*ktz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((cd.*(2.*betae.*eta.*G.*kptz - alphad.^2.*kpz).*M + alpha.^2.*ktz.*M.*md + ...
                    2.*eta.*G.*(ktz - (cd.*kpz + betae.*ktpz).*M).*md + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md)).*s + 2.*eta.*G.*((-kptz).*ktpr + kptr.*ktpz - kpz.*ktr + kpr.*ktz).*M.*md.*xi.^2).^2 - ...
                4.*M.*((-alphad.^2).*cd.*kptz.*s + alpha.*alphad.*ktz.*md.*s - 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + ...
                  2.*eta.*G.*(betae.*cd.*kpz.*M.*s - kpz.*ktpr.*M.*md.*xi.^2 + ktpz.*md.*(s + kpr.*M.*xi.^2))))))./(2.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + ...
             2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2))) - ((-alpha).*alphad.*cd.*kptz.*M.*s + 2.*betae.*cd.*eta.*G.*kptz.*M.*s - alphad.^2.*cd.*kpz.*M.*s + 2.*eta.*G.*ktz.*md.*s - ...
            2.*cd.*eta.*G.*kpz.*M.*md.*s + alpha.*alphad.*ktpz.*M.*md.*s - 2.*betae.*eta.*G.*ktpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - ...
            2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2 - eta.*G.*kptz.*ktpz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(...
                ((cd.*(2.*betae.*eta.*G.*kptz - alphad.^2.*kpz).*M + alpha.^2.*ktz.*M.*md + 2.*eta.*G.*(ktz - (cd.*kpz + betae.*ktpz).*M).*md + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md)).*s + ...
                  2.*eta.*G.*((-kptz).*ktpr + kptr.*ktpz - kpz.*ktr + kpr.*ktz).*M.*md.*xi.^2).^2 - 4.*M.*((-alphad.^2).*cd.*kptz.*s + alpha.*alphad.*ktz.*md.*s - 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + ...
                    (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s - kpz.*ktpr.*M.*md.*xi.^2 + ktpz.*md.*(s + kpr.*M.*xi.^2))))) + ...
            eta.*G.*kpz.*ktz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((cd.*(2.*betae.*eta.*G.*kptz - alphad.^2.*kpz).*M + alpha.^2.*ktz.*M.*md + 2.*eta.*G.*(ktz - (cd.*kpz + betae.*ktpz).*M).*md + ...
                    alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md)).*s + 2.*eta.*G.*((-kptz).*ktpr + kptr.*ktpz - kpz.*ktr + kpr.*ktz).*M.*md.*xi.^2).^2 - 4.*M.*((-alphad.^2).*cd.*kptz.*s + alpha.*alphad.*ktz.*md.*s - ...
                  2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s - kpz.*ktpr.*M.*md.*xi.^2 + ...
                    ktpz.*md.*(s + kpr.*M.*xi.^2))))))./(2.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2))))) + ...
       (xi.^3.*((alphad.^3.*cd.*kpz.*M + alpha.^2.*alphad.*ktz.*M.*md + 2.*alphad.*eta.*G.*((-betae).*cd.*kptz.*M - ktz.*md + cd.*kpz.*M.*md + betae.*ktpz.*M.*md) - ...
            alpha.*M.*(4.*eta.*G.*(cd.*kptz + betae.*ktz).*md + alphad.^2.*(cd.*kptz + ktpz.*md))).*s + 2.*eta.*G.*(alphad.*(kptz.*ktpr - kptr.*ktpz + kpz.*ktr - kpr.*ktz) + alpha.*(-2.*kptz.*ktr + 2.*kptr.*ktz)).*M.*md.*...
           xi.^2 - alphad.*eta.*G.*kptz.*ktpz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((cd.*(2.*betae.*eta.*G.*kptz - alphad.^2.*kpz).*M + alpha.^2.*ktz.*M.*md + ...
                  2.*eta.*G.*(ktz - (cd.*kpz + betae.*ktpz).*M).*md + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md)).*s + 2.*eta.*G.*((-kptz).*ktpr + kptr.*ktpz - kpz.*ktr + kpr.*ktz).*M.*md.*xi.^2).^2 - ...
              4.*M.*((-alphad.^2).*cd.*kptz.*s + alpha.*alphad.*ktz.*md.*s - 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + ...
                2.*eta.*G.*(betae.*cd.*kpz.*M.*s - kpz.*ktpr.*M.*md.*xi.^2 + ktpz.*md.*(s + kpr.*M.*xi.^2))))) + alphad.*eta.*G.*kpz.*ktz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*...
             (((cd.*(2.*betae.*eta.*G.*kptz - alphad.^2.*kpz).*M + alpha.^2.*ktz.*M.*md + 2.*eta.*G.*(ktz - (cd.*kpz + betae.*ktpz).*M).*md + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md)).*s + ...
                2.*eta.*G.*((-kptz).*ktpr + kptr.*ktpz - kpz.*ktr + kpr.*ktz).*M.*md.*xi.^2).^2 - 4.*M.*((-alphad.^2).*cd.*kptz.*s + alpha.*alphad.*ktz.*md.*s - 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + ...
                  (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s - kpz.*ktpr.*M.*md.*xi.^2 + ktpz.*md.*(s + kpr.*M.*xi.^2)))))).*...
         (-xi.^2 + (1./4).*((alpha.*alphad.*s - 2.*betae.*eta.*G.*s + 2.*eta.*G.*kptr.*xi.^2)./(eta.*G.*kptz) + (1./(eta.*G.*kptz.*(kptz.*ktpz - kpz.*ktz).*M.*md)).*...
             ((-(cd.*kptz.*((-alpha).*alphad.*kptz + 2.*betae.*eta.*G.*kptz + alphad.^2.*kpz).*M + alpha.*(alpha.*kptz - alphad.*kpz).*ktz.*M.*md + 2.*eta.*G.*(betae.*kpz.*ktz.*M + kptz.*(ktz + cd.*kpz.*M)).*md)).*s + ...
              2.*eta.*G.*(kptz.^2.*ktpr + kptr.*kpz.*ktz - kptz.*(kpz.*ktr + kpr.*ktz)).*M.*md.*xi.^2) - sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*...
              (((cd.*(2.*betae.*eta.*G.*kptz - alphad.^2.*kpz).*M + alpha.^2.*ktz.*M.*md + 2.*eta.*G.*(ktz - (cd.*kpz + betae.*ktpz).*M).*md + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md)).*s + ...
                 2.*eta.*G.*((-kptz).*ktpr + kptr.*ktpz - kpz.*ktr + kpr.*ktz).*M.*md.*xi.^2).^2 - 4.*M.*((-alphad.^2).*cd.*kptz.*s + alpha.*alphad.*ktz.*md.*s - 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + ...
                   (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s - kpz.*ktpr.*M.*md.*xi.^2 + ktpz.*md.*(s + kpr.*M.*xi.^2))))))).*...
         ((s.*((-cd).*(alphad + alpha.*betae.*M).*s + M.*(alphad.*cd.*(-kpr + kpz) + alpha.*(ktpr - ktpz).*md).*xi.^2))./(cd.*(alphad.^2 + 2.*alpha.*alphad.*betae.*M - 2.*betae.^2.*eta.*G.*M + 2.*eta.*G.*md + alpha.^2.*M.*md).*...
             s.^2 + (cd.*(2.*betae.*eta.*G.*(kptr - kptz) + alpha.*alphad.*(-kptr + kptz) + alphad.^2.*(kpr - kpz)).*M + (alpha.*(alphad.*(-ktpr + ktpz) + alpha.*(ktr - ktz)).*M + ...
                2.*eta.*G.*(ktr - ktz + cd.*(kpr - kpz).*M + betae.*(ktpr - ktpz).*M)).*md).*s.*xi.^2 + 2.*eta.*G.*((-(kptr - kptz)).*(ktpr - ktpz) + (kpr - kpz).*(ktr - ktz)).*M.*md.*xi.^4) - ...
          (s.*((-cd).*(alphad.*betae + alpha.*md).*s + (alphad.*cd.*(kptr - kptz) + alpha.*(-ktr + ktz).*md).*xi.^2).*((-alpha).*alphad.*cd.*kptz.*M.*s + 2.*betae.*cd.*eta.*G.*kptz.*M.*s - alphad.^2.*cd.*kpz.*M.*s + ...
             2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + alpha.*alphad.*ktpz.*M.*md.*s - 2.*betae.*eta.*G.*ktpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - ...
             2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2 - eta.*G.*kptz.*ktpz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*...
                (((cd.*(2.*betae.*eta.*G.*kptz - alphad.^2.*kpz).*M + alpha.^2.*ktz.*M.*md + 2.*eta.*G.*(ktz - (cd.*kpz + betae.*ktpz).*M).*md + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md)).*s + ...
                   2.*eta.*G.*((-kptz).*ktpr + kptr.*ktpz - kpz.*ktr + kpr.*ktz).*M.*md.*xi.^2).^2 - 4.*M.*((-alphad.^2).*cd.*kptz.*s + alpha.*alphad.*ktz.*md.*s - 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + ...
                     (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s - kpz.*ktpr.*M.*md.*xi.^2 + ktpz.*md.*(s + kpr.*M.*xi.^2))))) + ...
             eta.*G.*kpz.*ktz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((cd.*(2.*betae.*eta.*G.*kptz - alphad.^2.*kpz).*M + alpha.^2.*ktz.*M.*md + 2.*eta.*G.*(ktz - (cd.*kpz + betae.*ktpz).*M).*md + ...
                     alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md)).*s + 2.*eta.*G.*((-kptz).*ktpr + kptr.*ktpz - kpz.*ktr + kpr.*ktz).*M.*md.*xi.^2).^2 - 4.*M.*((-alphad.^2).*cd.*kptz.*s + alpha.*alphad.*ktz.*md.*s - ...
                   2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s - kpz.*ktpr.*M.*md.*xi.^2 + ...
                     ktpz.*md.*(s + kpr.*M.*xi.^2)))))))./(2.*(cd.*(alphad.^2 + 2.*alpha.*alphad.*betae.*M - 2.*betae.^2.*eta.*G.*M + 2.*eta.*G.*md + alpha.^2.*M.*md).*s.^2 + ...
             (cd.*(2.*betae.*eta.*G.*(kptr - kptz) + alpha.*alphad.*(-kptr + kptz) + alphad.^2.*(kpr - kpz)).*M + (alpha.*(alphad.*(-ktpr + ktpz) + alpha.*(ktr - ktz)).*M + ...
                 2.*eta.*G.*(ktr - ktz + cd.*(kpr - kpz).*M + betae.*(ktpr - ktpz).*M)).*md).*s.*xi.^2 + 2.*eta.*G.*((-(kptr - kptz)).*(ktpr - ktpz) + (kpr - kpz).*(ktr - ktz)).*M.*md.*xi.^4).*...
            (alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)))))./...
        (2.*eta.*G.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)))).*tanh(h.*xi) + ...
     (xi.^2.*sqrt((alpha.*alphad.*s - 2.*betae.*eta.*G.*s + 2.*eta.*G.*kptr.*xi.^2)./(eta.*G.*kptz) + (1./(eta.*G.*kptz.*(kptz.*ktpz - kpz.*ktz).*M.*md)).*...
          ((-(cd.*kptz.*((-alpha).*alphad.*kptz + 2.*betae.*eta.*G.*kptz + alphad.^2.*kpz).*M + alpha.*(alpha.*kptz - alphad.*kpz).*ktz.*M.*md + 2.*eta.*G.*(betae.*kpz.*ktz.*M + kptz.*(ktz + cd.*kpz.*M)).*md)).*s + ...
           2.*eta.*G.*(kptz.^2.*ktpr + kptr.*kpz.*ktz - kptz.*(kpz.*ktr + kpr.*ktz)).*M.*md.*xi.^2) - sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*...
           (((cd.*(2.*betae.*eta.*G.*kptz - alphad.^2.*kpz).*M + alpha.^2.*ktz.*M.*md + 2.*eta.*G.*(ktz - (cd.*kpz + betae.*ktpz).*M).*md + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md)).*s + ...
              2.*eta.*G.*((-kptz).*ktpr + kptr.*ktpz - kpz.*ktr + kpr.*ktz).*M.*md.*xi.^2).^2 - 4.*M.*((-alphad.^2).*cd.*kptz.*s + alpha.*alphad.*ktz.*md.*s - 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + ...
                (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s - kpz.*ktpr.*M.*md.*xi.^2 + ktpz.*md.*(s + kpr.*M.*xi.^2)))))).*...
       ((alphad.^3.*cd.*kpz.*M + alpha.^2.*alphad.*ktz.*M.*md + 2.*alphad.*eta.*G.*((-betae).*cd.*kptz.*M - ktz.*md + cd.*kpz.*M.*md + betae.*ktpz.*M.*md) - ...
          alpha.*M.*(4.*eta.*G.*(cd.*kptz + betae.*ktz).*md + alphad.^2.*(cd.*kptz + ktpz.*md))).*s + 2.*eta.*G.*(alphad.*(kptz.*ktpr - kptr.*ktpz + kpz.*ktr - kpr.*ktz) + alpha.*(-2.*kptz.*ktr + 2.*kptr.*ktz)).*M.*md.*xi.^2 + ...
        alphad.*eta.*G.*kptz.*ktpz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((cd.*(2.*betae.*eta.*G.*kptz - alphad.^2.*kpz).*M + alpha.^2.*ktz.*M.*md + 2.*eta.*G.*(ktz - (cd.*kpz + betae.*ktpz).*M).*...
                 md + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md)).*s + 2.*eta.*G.*((-kptz).*ktpr + kptr.*ktpz - kpz.*ktr + kpr.*ktz).*M.*md.*xi.^2).^2 - ...
            4.*M.*((-alphad.^2).*cd.*kptz.*s + alpha.*alphad.*ktz.*md.*s - 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + ...
              2.*eta.*G.*(betae.*cd.*kpz.*M.*s - kpz.*ktpr.*M.*md.*xi.^2 + ktpz.*md.*(s + kpr.*M.*xi.^2))))) - alphad.*eta.*G.*kpz.*ktz.*M.*md.*...
         sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((cd.*(2.*betae.*eta.*G.*kptz - alphad.^2.*kpz).*M + alpha.^2.*ktz.*M.*md + 2.*eta.*G.*(ktz - (cd.*kpz + betae.*ktpz).*M).*md + ...
                alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md)).*s + 2.*eta.*G.*((-kptz).*ktpr + kptr.*ktpz - kpz.*ktr + kpr.*ktz).*M.*md.*xi.^2).^2 - 4.*M.*((-alphad.^2).*cd.*kptz.*s + alpha.*alphad.*ktz.*md.*s - ...
              2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s - kpz.*ktpr.*M.*md.*xi.^2 + ...
                ktpz.*md.*(s + kpr.*M.*xi.^2)))))).*(-xi.^2 + (1./4).*((alpha.*alphad.*s - 2.*betae.*eta.*G.*s + 2.*eta.*G.*kptr.*xi.^2)./(eta.*G.*kptz) + (1./(eta.*G.*kptz.*(kptz.*ktpz - kpz.*ktz).*M.*md)).*...
           ((-(cd.*kptz.*((-alpha).*alphad.*kptz + 2.*betae.*eta.*G.*kptz + alphad.^2.*kpz).*M + alpha.*(alpha.*kptz - alphad.*kpz).*ktz.*M.*md + 2.*eta.*G.*(betae.*kpz.*ktz.*M + kptz.*(ktz + cd.*kpz.*M)).*md)).*s + ...
            2.*eta.*G.*(kptz.^2.*ktpr + kptr.*kpz.*ktz - kptz.*(kpz.*ktr + kpr.*ktz)).*M.*md.*xi.^2) + sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*...
            (((cd.*(2.*betae.*eta.*G.*kptz - alphad.^2.*kpz).*M + alpha.^2.*ktz.*M.*md + 2.*eta.*G.*(ktz - (cd.*kpz + betae.*ktpz).*M).*md + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md)).*s + 2.*eta.*G.*...
                ((-kptz).*ktpr + kptr.*ktpz - kpz.*ktr + kpr.*ktz).*M.*md.*xi.^2).^2 - 4.*M.*((-alphad.^2).*cd.*kptz.*s + alpha.*alphad.*ktz.*md.*s - 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + ...
                 (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s - kpz.*ktpr.*M.*md.*xi.^2 + ktpz.*md.*(s + kpr.*M.*xi.^2))))))).*...
       ((s.*((-cd).*(alphad + alpha.*betae.*M).*s + M.*(alphad.*cd.*(-kpr + kpz) + alpha.*(ktpr - ktpz).*md).*xi.^2))./(cd.*(alphad.^2 + 2.*alpha.*alphad.*betae.*M - 2.*betae.^2.*eta.*G.*M + 2.*eta.*G.*md + alpha.^2.*M.*md).*...
           s.^2 + (cd.*(2.*betae.*eta.*G.*(kptr - kptz) + alpha.*alphad.*(-kptr + kptz) + alphad.^2.*(kpr - kpz)).*M + (alpha.*(alphad.*(-ktpr + ktpz) + alpha.*(ktr - ktz)).*M + ...
              2.*eta.*G.*(ktr - ktz + cd.*(kpr - kpz).*M + betae.*(ktpr - ktpz).*M)).*md).*s.*xi.^2 + 2.*eta.*G.*((-(kptr - kptz)).*(ktpr - ktpz) + (kpr - kpz).*(ktr - ktz)).*M.*md.*xi.^4) - ...
        (s.*((-cd).*(alphad.*betae + alpha.*md).*s + (alphad.*cd.*(kptr - kptz) + alpha.*(-ktr + ktz).*md).*xi.^2).*((-alpha).*alphad.*cd.*kptz.*M.*s + 2.*betae.*cd.*eta.*G.*kptz.*M.*s - alphad.^2.*cd.*kpz.*M.*s + ...
           2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + alpha.*alphad.*ktpz.*M.*md.*s - 2.*betae.*eta.*G.*ktpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - ...
           2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2 + eta.*G.*kptz.*ktpz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*...
              (((cd.*(2.*betae.*eta.*G.*kptz - alphad.^2.*kpz).*M + alpha.^2.*ktz.*M.*md + 2.*eta.*G.*(ktz - (cd.*kpz + betae.*ktpz).*M).*md + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md)).*s + ...
                 2.*eta.*G.*((-kptz).*ktpr + kptr.*ktpz - kpz.*ktr + kpr.*ktz).*M.*md.*xi.^2).^2 - 4.*M.*((-alphad.^2).*cd.*kptz.*s + alpha.*alphad.*ktz.*md.*s - 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + ...
                   (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s - kpz.*ktpr.*M.*md.*xi.^2 + ktpz.*md.*(s + kpr.*M.*xi.^2))))) - ...
           eta.*G.*kpz.*ktz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((cd.*(2.*betae.*eta.*G.*kptz - alphad.^2.*kpz).*M + alpha.^2.*ktz.*M.*md + 2.*eta.*G.*(ktz - (cd.*kpz + betae.*ktpz).*M).*md + ...
                   alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md)).*s + 2.*eta.*G.*((-kptz).*ktpr + kptr.*ktpz - kpz.*ktr + kpr.*ktz).*M.*md.*xi.^2).^2 - 4.*M.*((-alphad.^2).*cd.*kptz.*s + alpha.*alphad.*ktz.*md.*s - ...
                 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s - kpz.*ktpr.*M.*md.*xi.^2 + ...
                   ktpz.*md.*(s + kpr.*M.*xi.^2)))))))./(2.*(cd.*(alphad.^2 + 2.*alpha.*alphad.*betae.*M - 2.*betae.^2.*eta.*G.*M + 2.*eta.*G.*md + alpha.^2.*M.*md).*s.^2 + ...
           (cd.*(2.*betae.*eta.*G.*(kptr - kptz) + alpha.*alphad.*(-kptr + kptz) + alphad.^2.*(kpr - kpz)).*M + (alpha.*(alphad.*(-ktpr + ktpz) + alpha.*(ktr - ktz)).*M + 2.*eta.*G.*...
                (ktr - ktz + cd.*(kpr - kpz).*M + betae.*(ktpr - ktpz).*M)).*md).*s.*xi.^2 + 2.*eta.*G.*((-(kptr - kptz)).*(ktpr - ktpz) + (kpr - kpz).*(ktr - ktz)).*M.*md.*xi.^4).*...
          (alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)))).*...
       tanh((1./2).*h.*sqrt((alpha.*alphad.*s - 2.*betae.*eta.*G.*s + 2.*eta.*G.*kptr.*xi.^2)./(eta.*G.*kptz) + (1./(eta.*G.*kptz.*(kptz.*ktpz - kpz.*ktz).*M.*md)).*...
            ((-(cd.*kptz.*((-alpha).*alphad.*kptz + 2.*betae.*eta.*G.*kptz + alphad.^2.*kpz).*M + alpha.*(alpha.*kptz - alphad.*kpz).*ktz.*M.*md + 2.*eta.*G.*(betae.*kpz.*ktz.*M + kptz.*(ktz + cd.*kpz.*M)).*md)).*s + ...
             2.*eta.*G.*(kptz.^2.*ktpr + kptr.*kpz.*ktz - kptz.*(kpz.*ktr + kpr.*ktz)).*M.*md.*xi.^2) - sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*...
             (((cd.*(2.*betae.*eta.*G.*kptz - alphad.^2.*kpz).*M + alpha.^2.*ktz.*M.*md + 2.*eta.*G.*(ktz - (cd.*kpz + betae.*ktpz).*M).*md + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md)).*s + ...
                2.*eta.*G.*((-kptz).*ktpr + kptr.*ktpz - kpz.*ktr + kpr.*ktz).*M.*md.*xi.^2).^2 - 4.*M.*((-alphad.^2).*cd.*kptz.*s + alpha.*alphad.*ktz.*md.*s - 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + ...
                  (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s - kpz.*ktpr.*M.*md.*xi.^2 + ktpz.*md.*(s + kpr.*M.*xi.^2))))))))./...
      (4.*eta.*G.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2))) + ...
     (xi.^2.*sqrt((alpha.*alphad.*s - 2.*betae.*eta.*G.*s + 2.*eta.*G.*kptr.*xi.^2)./(eta.*G.*kptz) + (1./(eta.*G.*kptz.*(kptz.*ktpz - kpz.*ktz).*M.*md)).*...
          ((-(cd.*kptz.*((-alpha).*alphad.*kptz + 2.*betae.*eta.*G.*kptz + alphad.^2.*kpz).*M + alpha.*(alpha.*kptz - alphad.*kpz).*ktz.*M.*md + 2.*eta.*G.*(betae.*kpz.*ktz.*M + kptz.*(ktz + cd.*kpz.*M)).*md)).*s + ...
           2.*eta.*G.*(kptz.^2.*ktpr + kptr.*kpz.*ktz - kptz.*(kpz.*ktr + kpr.*ktz)).*M.*md.*xi.^2) + sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*...
           (((cd.*(2.*betae.*eta.*G.*kptz - alphad.^2.*kpz).*M + alpha.^2.*ktz.*M.*md + 2.*eta.*G.*(ktz - (cd.*kpz + betae.*ktpz).*M).*md + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md)).*s + ...
              2.*eta.*G.*((-kptz).*ktpr + kptr.*ktpz - kpz.*ktr + kpr.*ktz).*M.*md.*xi.^2).^2 - 4.*M.*((-alphad.^2).*cd.*kptz.*s + alpha.*alphad.*ktz.*md.*s - 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + ...
                (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s - kpz.*ktpr.*M.*md.*xi.^2 + ktpz.*md.*(s + kpr.*M.*xi.^2)))))).*...
       ((alphad.^3.*cd.*kpz.*M + alpha.^2.*alphad.*ktz.*M.*md + 2.*alphad.*eta.*G.*((-betae).*cd.*kptz.*M - ktz.*md + cd.*kpz.*M.*md + betae.*ktpz.*M.*md) - ...
          alpha.*M.*(4.*eta.*G.*(cd.*kptz + betae.*ktz).*md + alphad.^2.*(cd.*kptz + ktpz.*md))).*s + 2.*eta.*G.*(alphad.*(kptz.*ktpr - kptr.*ktpz + kpz.*ktr - kpr.*ktz) + alpha.*(-2.*kptz.*ktr + 2.*kptr.*ktz)).*M.*md.*xi.^2 - ...
        alphad.*eta.*G.*kptz.*ktpz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((cd.*(2.*betae.*eta.*G.*kptz - alphad.^2.*kpz).*M + alpha.^2.*ktz.*M.*md + 2.*eta.*G.*(ktz - (cd.*kpz + betae.*ktpz).*M).*...
                 md + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md)).*s + 2.*eta.*G.*((-kptz).*ktpr + kptr.*ktpz - kpz.*ktr + kpr.*ktz).*M.*md.*xi.^2).^2 - ...
            4.*M.*((-alphad.^2).*cd.*kptz.*s + alpha.*alphad.*ktz.*md.*s - 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + ...
              2.*eta.*G.*(betae.*cd.*kpz.*M.*s - kpz.*ktpr.*M.*md.*xi.^2 + ktpz.*md.*(s + kpr.*M.*xi.^2))))) + alphad.*eta.*G.*kpz.*ktz.*M.*md.*...
         sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((cd.*(2.*betae.*eta.*G.*kptz - alphad.^2.*kpz).*M + alpha.^2.*ktz.*M.*md + 2.*eta.*G.*(ktz - (cd.*kpz + betae.*ktpz).*M).*md + ...
                alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md)).*s + 2.*eta.*G.*((-kptz).*ktpr + kptr.*ktpz - kpz.*ktr + kpr.*ktz).*M.*md.*xi.^2).^2 - 4.*M.*((-alphad.^2).*cd.*kptz.*s + alpha.*alphad.*ktz.*md.*s - ...
              2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s - kpz.*ktpr.*M.*md.*xi.^2 + ...
                ktpz.*md.*(s + kpr.*M.*xi.^2)))))).*(xi.^2 + (1./4).*(-((alpha.*alphad.*s - 2.*betae.*eta.*G.*s + 2.*eta.*G.*kptr.*xi.^2)./(eta.*G.*kptz)) - (1./(eta.*G.*kptz.*(kptz.*ktpz - kpz.*ktz).*M.*md)).*...
           ((-(cd.*kptz.*((-alpha).*alphad.*kptz + 2.*betae.*eta.*G.*kptz + alphad.^2.*kpz).*M + alpha.*(alpha.*kptz - alphad.*kpz).*ktz.*M.*md + 2.*eta.*G.*(betae.*kpz.*ktz.*M + kptz.*(ktz + cd.*kpz.*M)).*md)).*s + ...
            2.*eta.*G.*(kptz.^2.*ktpr + kptr.*kpz.*ktz - kptz.*(kpz.*ktr + kpr.*ktz)).*M.*md.*xi.^2) + sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*...
            (((cd.*(2.*betae.*eta.*G.*kptz - alphad.^2.*kpz).*M + alpha.^2.*ktz.*M.*md + 2.*eta.*G.*(ktz - (cd.*kpz + betae.*ktpz).*M).*md + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md)).*s + 2.*eta.*G.*...
                ((-kptz).*ktpr + kptr.*ktpz - kpz.*ktr + kpr.*ktz).*M.*md.*xi.^2).^2 - 4.*M.*((-alphad.^2).*cd.*kptz.*s + alpha.*alphad.*ktz.*md.*s - 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + ...
                 (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s - kpz.*ktpr.*M.*md.*xi.^2 + ktpz.*md.*(s + kpr.*M.*xi.^2))))))).*...
       ((s.*((-cd).*(alphad + alpha.*betae.*M).*s + M.*(alphad.*cd.*(-kpr + kpz) + alpha.*(ktpr - ktpz).*md).*xi.^2))./(cd.*(alphad.^2 + 2.*alpha.*alphad.*betae.*M - 2.*betae.^2.*eta.*G.*M + 2.*eta.*G.*md + alpha.^2.*M.*md).*...
           s.^2 + (cd.*(2.*betae.*eta.*G.*(kptr - kptz) + alpha.*alphad.*(-kptr + kptz) + alphad.^2.*(kpr - kpz)).*M + (alpha.*(alphad.*(-ktpr + ktpz) + alpha.*(ktr - ktz)).*M + ...
              2.*eta.*G.*(ktr - ktz + cd.*(kpr - kpz).*M + betae.*(ktpr - ktpz).*M)).*md).*s.*xi.^2 + 2.*eta.*G.*((-(kptr - kptz)).*(ktpr - ktpz) + (kpr - kpz).*(ktr - ktz)).*M.*md.*xi.^4) - ...
        (s.*((-cd).*(alphad.*betae + alpha.*md).*s + (alphad.*cd.*(kptr - kptz) + alpha.*(-ktr + ktz).*md).*xi.^2).*((-alpha).*alphad.*cd.*kptz.*M.*s + 2.*betae.*cd.*eta.*G.*kptz.*M.*s - alphad.^2.*cd.*kpz.*M.*s + ...
           2.*eta.*G.*ktz.*md.*s - 2.*cd.*eta.*G.*kpz.*M.*md.*s + alpha.*alphad.*ktpz.*M.*md.*s - 2.*betae.*eta.*G.*ktpz.*M.*md.*s + alpha.^2.*ktz.*M.*md.*s - 2.*eta.*G.*kptz.*ktpr.*M.*md.*xi.^2 + 2.*eta.*G.*kptr.*ktpz.*M.*md.*xi.^2 - ...
           2.*eta.*G.*kpz.*ktr.*M.*md.*xi.^2 + 2.*eta.*G.*kpr.*ktz.*M.*md.*xi.^2 - eta.*G.*kptz.*ktpz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*...
              (((cd.*(2.*betae.*eta.*G.*kptz - alphad.^2.*kpz).*M + alpha.^2.*ktz.*M.*md + 2.*eta.*G.*(ktz - (cd.*kpz + betae.*ktpz).*M).*md + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md)).*s + ...
                 2.*eta.*G.*((-kptz).*ktpr + kptr.*ktpz - kpz.*ktr + kpr.*ktz).*M.*md.*xi.^2).^2 - 4.*M.*((-alphad.^2).*cd.*kptz.*s + alpha.*alphad.*ktz.*md.*s - 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + ...
                   (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s - kpz.*ktpr.*M.*md.*xi.^2 + ktpz.*md.*(s + kpr.*M.*xi.^2))))) + ...
           eta.*G.*kpz.*ktz.*M.*md.*sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*(((cd.*(2.*betae.*eta.*G.*kptz - alphad.^2.*kpz).*M + alpha.^2.*ktz.*M.*md + 2.*eta.*G.*(ktz - (cd.*kpz + betae.*ktpz).*M).*md + ...
                   alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md)).*s + 2.*eta.*G.*((-kptz).*ktpr + kptr.*ktpz - kpz.*ktr + kpr.*ktz).*M.*md.*xi.^2).^2 - 4.*M.*((-alphad.^2).*cd.*kptz.*s + alpha.*alphad.*ktz.*md.*s - ...
                 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s - kpz.*ktpr.*M.*md.*xi.^2 + ...
                   ktpz.*md.*(s + kpr.*M.*xi.^2)))))))./(2.*(cd.*(alphad.^2 + 2.*alpha.*alphad.*betae.*M - 2.*betae.^2.*eta.*G.*M + 2.*eta.*G.*md + alpha.^2.*M.*md).*s.^2 + ...
           (cd.*(2.*betae.*eta.*G.*(kptr - kptz) + alpha.*alphad.*(-kptr + kptz) + alphad.^2.*(kpr - kpz)).*M + (alpha.*(alphad.*(-ktpr + ktpz) + alpha.*(ktr - ktz)).*M + 2.*eta.*G.*...
                (ktr - ktz + cd.*(kpr - kpz).*M + betae.*(ktpr - ktpz).*M)).*md).*s.*xi.^2 + 2.*eta.*G.*((-(kptr - kptz)).*(ktpr - ktpz) + (kpr - kpz).*(ktr - ktz)).*M.*md.*xi.^4).*...
          (alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2)))).*...
       tanh((1./2).*h.*sqrt((alpha.*alphad.*s - 2.*betae.*eta.*G.*s + 2.*eta.*G.*kptr.*xi.^2)./(eta.*G.*kptz) + (1./(eta.*G.*kptz.*(kptz.*ktpz - kpz.*ktz).*M.*md)).*...
            ((-(cd.*kptz.*((-alpha).*alphad.*kptz + 2.*betae.*eta.*G.*kptz + alphad.^2.*kpz).*M + alpha.*(alpha.*kptz - alphad.*kpz).*ktz.*M.*md + 2.*eta.*G.*(betae.*kpz.*ktz.*M + kptz.*(ktz + cd.*kpz.*M)).*md)).*s + ...
             2.*eta.*G.*(kptz.^2.*ktpr + kptr.*kpz.*ktz - kptz.*(kpz.*ktr + kpr.*ktz)).*M.*md.*xi.^2) + sqrt((1./(eta.^2.*G.^2.*(kptz.*ktpz - kpz.*ktz).^2.*M.^2.*md.^2)).*...
             (((cd.*(2.*betae.*eta.*G.*kptz - alphad.^2.*kpz).*M + alpha.^2.*ktz.*M.*md + 2.*eta.*G.*(ktz - (cd.*kpz + betae.*ktpz).*M).*md + alpha.*alphad.*M.*((-cd).*kptz + ktpz.*md)).*s + ...
                2.*eta.*G.*((-kptz).*ktpr + kptr.*ktpz - kpz.*ktr + kpr.*ktz).*M.*md.*xi.^2).^2 - 4.*M.*((-alphad.^2).*cd.*kptz.*s + alpha.*alphad.*ktz.*md.*s - 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + ...
                  (kptz.*ktr - kptr.*ktz).*xi.^2)).*((-alpha).*alphad.*cd.*kpz.*M.*s + alpha.^2.*ktpz.*M.*md.*s + 2.*eta.*G.*(betae.*cd.*kpz.*M.*s - kpz.*ktpr.*M.*md.*xi.^2 + ktpz.*md.*(s + kpr.*M.*xi.^2))))))))./...
      (4.*eta.*G.*M.*(alphad.^2.*cd.*kptz.*s - alpha.*alphad.*ktz.*md.*s + 2.*eta.*G.*md.*(cd.*kptz.*s + betae.*ktz.*s + (kptz.*ktr - kptr.*ktz).*xi.^2))))));
end